/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */  
package GBI_SalesApp.intrnl;

public class BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERSMetaData
extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERSMetaData()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getMetaData());
        _init();
    }
    
    protected void _init()
    {
        setId(15);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData PARTN_ROLE_attribute = addAttributeWithParams
        	(307, "PARTN_ROLE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PARTN_NUMB_attribute = addAttributeWithParams
        	(308, "PARTN_NUMB", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ITM_NUMBER_attribute = addAttributeWithParams
        	(309, "ITM_NUMBER", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TITLE_attribute = addAttributeWithParams
        	(310, "TITLE", "string", 
        	15, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(15)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NAME_attribute = addAttributeWithParams
        	(311, "NAME", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NAME_2_attribute = addAttributeWithParams
        	(312, "NAME_2", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NAME_3_attribute = addAttributeWithParams
        	(313, "NAME_3", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NAME_4_attribute = addAttributeWithParams
        	(314, "NAME_4", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData STREET_attribute = addAttributeWithParams
        	(315, "STREET", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COUNTRY_attribute = addAttributeWithParams
        	(316, "COUNTRY", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COUNTR_ISO_attribute = addAttributeWithParams
        	(317, "COUNTR_ISO", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData POSTL_CODE_attribute = addAttributeWithParams
        	(318, "POSTL_CODE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData POBX_PCD_attribute = addAttributeWithParams
        	(319, "POBX_PCD", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData POBX_CTY_attribute = addAttributeWithParams
        	(320, "POBX_CTY", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CITY_attribute = addAttributeWithParams
        	(321, "CITY", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DISTRICT_attribute = addAttributeWithParams
        	(322, "DISTRICT", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REGION_attribute = addAttributeWithParams
        	(323, "REGION", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_BOX_attribute = addAttributeWithParams
        	(324, "PO_BOX", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TELEPHONE_attribute = addAttributeWithParams
        	(325, "TELEPHONE", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TELEPHONE2_attribute = addAttributeWithParams
        	(326, "TELEPHONE2", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TELEBOX_attribute = addAttributeWithParams
        	(327, "TELEBOX", "string", 
        	15, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(15)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FAX_NUMBER_attribute = addAttributeWithParams
        	(328, "FAX_NUMBER", "string", 
        	31, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(31)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TELETEX_NO_attribute = addAttributeWithParams
        	(329, "TELETEX_NO", "string", 
        	30, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(30)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TELEX_NO_attribute = addAttributeWithParams
        	(330, "TELEX_NO", "string", 
        	30, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(30)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LANGU_attribute = addAttributeWithParams
        	(331, "LANGU", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LANGU_ISO_attribute = addAttributeWithParams
        	(332, "LANGU_ISO", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UNLOAD_PT_attribute = addAttributeWithParams
        	(333, "UNLOAD_PT", "string", 
        	25, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(25)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TRANSPZONE_attribute = addAttributeWithParams
        	(334, "TRANSPZONE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXJURCODE_attribute = addAttributeWithParams
        	(335, "TAXJURCODE", "string", 
        	15, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(15)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADDRESS_attribute = addAttributeWithParams
        	(336, "ADDRESS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRIV_ADDR_attribute = addAttributeWithParams
        	(337, "PRIV_ADDR", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADDR_TYPE_attribute = addAttributeWithParams
        	(338, "ADDR_TYPE", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADDR_ORIG_attribute = addAttributeWithParams
        	(339, "ADDR_ORIG", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADDR_LINK_attribute = addAttributeWithParams
        	(340, "ADDR_LINK", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFOBJTYPE_attribute = addAttributeWithParams
        	(341, "REFOBJTYPE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFOBJKEY_attribute = addAttributeWithParams
        	(342, "REFOBJKEY", "string", 
        	70, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(70)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFLOGSYS_attribute = addAttributeWithParams
        	(343, "REFLOGSYS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERS");
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}