/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */  
package GBI_SalesApp.intrnl;

public class PersonalizationParametersMetaData
extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public PersonalizationParametersMetaData()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getMetaData());
        _init();
    }
    
    protected void _init()
    {
        setId(19);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData PK_GetDetail_attribute = addAttributeWithParams
        	(537, "PK_GetDetail", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "0000012000", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PK_GetDetailUserDefined_attribute = addAttributeWithParams
        	(538, "PK_GetDetailUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PK_GetList_attribute = addAttributeWithParams
        	(539, "PK_GetList", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "0000012000", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PK_GetListUserDefined_attribute = addAttributeWithParams
        	(540, "PK_GetListUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PK_GetStatus_attribute = addAttributeWithParams
        	(541, "PK_GetStatus", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "0000000001", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PK_GetStatusUserDefined_attribute = addAttributeWithParams
        	(542, "PK_GetStatusUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData username_attribute = addAttributeWithParams
        	(543, "username", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	false, false, true);
        com.sybase.reflection.AttributeMetaData usernameUserDefined_attribute = addAttributeWithParams
        	(544, "usernameUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData password_attribute = addAttributeWithParams
        	(545, "password", "string", 
        	-1, 
        	false, false, true, false, false, 
        	true,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	true, false, true);
        com.sybase.reflection.AttributeMetaData passwordUserDefined_attribute = addAttributeWithParams
        	(546, "passwordUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("PersonalizationParameters");
        setSuperClassDefined(true);
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}