/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERS extends com.sybase.persistence.AbstractStructure implements com.sybase.reflection.ClassWithMetaData
{
    private static GBI_SalesApp.intrnl.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERSMetaData META_DATA = new GBI_SalesApp.intrnl.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERSMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERS", GBI_SalesApp.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERS.class, META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
    
    /**
     * Creates an instance of GBI_SalesApp.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERS  
     */
    public BAPI_SALESORDER_CREATEFROMDAT2_ORDER_PARTNERS()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    
    private java.lang.String __PARTN_ROLE ;  
    
    private java.lang.String __PARTN_NUMB ;  
    
    private java.lang.String __ITM_NUMBER ;  
    
    private java.lang.String __TITLE ;  
    
    private java.lang.String __NAME ;  
    
    private java.lang.String __NAME_2 ;  
    
    private java.lang.String __NAME_3 ;  
    
    private java.lang.String __NAME_4 ;  
    
    private java.lang.String __STREET ;  
    
    private java.lang.String __COUNTRY ;  
    
    private java.lang.String __COUNTR_ISO ;  
    
    private java.lang.String __POSTL_CODE ;  
    
    private java.lang.String __POBX_PCD ;  
    
    private java.lang.String __POBX_CTY ;  
    
    private java.lang.String __CITY ;  
    
    private java.lang.String __DISTRICT ;  
    
    private java.lang.String __REGION ;  
    
    private java.lang.String __PO_BOX ;  
    
    private java.lang.String __TELEPHONE ;  
    
    private java.lang.String __TELEPHONE2 ;  
    
    private java.lang.String __TELEBOX ;  
    
    private java.lang.String __FAX_NUMBER ;  
    
    private java.lang.String __TELETEX_NO ;  
    
    private java.lang.String __TELEX_NO ;  
    
    private java.lang.String __LANGU ;  
    
    private java.lang.String __LANGU_ISO ;  
    
    private java.lang.String __UNLOAD_PT ;  
    
    private java.lang.String __TRANSPZONE ;  
    
    private java.lang.String __TAXJURCODE ;  
    
    private java.lang.String __ADDRESS ;  
    
    private java.lang.String __PRIV_ADDR ;  
    
    private java.lang.String __ADDR_TYPE ;  
    
    private java.lang.String __ADDR_ORIG ;  
    
    private java.lang.String __ADDR_LINK ;  
    
    private java.lang.String __REFOBJTYPE ;  
    
    private java.lang.String __REFOBJKEY ;  
    
    private java.lang.String __REFLOGSYS ;  
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 307:
            return getPARTN_ROLE();
        case 308:
            return getPARTN_NUMB();
        case 309:
            return getITM_NUMBER();
        case 310:
            return getTITLE();
        case 311:
            return getNAME();
        case 312:
            return getNAME_2();
        case 313:
            return getNAME_3();
        case 314:
            return getNAME_4();
        case 315:
            return getSTREET();
        case 316:
            return getCOUNTRY();
        case 317:
            return getCOUNTR_ISO();
        case 318:
            return getPOSTL_CODE();
        case 319:
            return getPOBX_PCD();
        case 320:
            return getPOBX_CTY();
        case 321:
            return getCITY();
        case 322:
            return getDISTRICT();
        case 323:
            return getREGION();
        case 324:
            return getPO_BOX();
        case 325:
            return getTELEPHONE();
        case 326:
            return getTELEPHONE2();
        case 327:
            return getTELEBOX();
        case 328:
            return getFAX_NUMBER();
        case 329:
            return getTELETEX_NO();
        case 330:
            return getTELEX_NO();
        case 331:
            return getLANGU();
        case 332:
            return getLANGU_ISO();
        case 333:
            return getUNLOAD_PT();
        case 334:
            return getTRANSPZONE();
        case 335:
            return getTAXJURCODE();
        case 336:
            return getADDRESS();
        case 337:
            return getPRIV_ADDR();
        case 338:
            return getADDR_TYPE();
        case 339:
            return getADDR_ORIG();
        case 340:
            return getADDR_LINK();
        case 341:
            return getREFOBJTYPE();
        case 342:
            return getREFOBJKEY();
        case 343:
            return getREFLOGSYS();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 307:
            setPARTN_ROLE((java.lang.String)v);
            break;
        case 308:
            setPARTN_NUMB((java.lang.String)v);
            break;
        case 309:
            setITM_NUMBER((java.lang.String)v);
            break;
        case 310:
            setTITLE((java.lang.String)v);
            break;
        case 311:
            setNAME((java.lang.String)v);
            break;
        case 312:
            setNAME_2((java.lang.String)v);
            break;
        case 313:
            setNAME_3((java.lang.String)v);
            break;
        case 314:
            setNAME_4((java.lang.String)v);
            break;
        case 315:
            setSTREET((java.lang.String)v);
            break;
        case 316:
            setCOUNTRY((java.lang.String)v);
            break;
        case 317:
            setCOUNTR_ISO((java.lang.String)v);
            break;
        case 318:
            setPOSTL_CODE((java.lang.String)v);
            break;
        case 319:
            setPOBX_PCD((java.lang.String)v);
            break;
        case 320:
            setPOBX_CTY((java.lang.String)v);
            break;
        case 321:
            setCITY((java.lang.String)v);
            break;
        case 322:
            setDISTRICT((java.lang.String)v);
            break;
        case 323:
            setREGION((java.lang.String)v);
            break;
        case 324:
            setPO_BOX((java.lang.String)v);
            break;
        case 325:
            setTELEPHONE((java.lang.String)v);
            break;
        case 326:
            setTELEPHONE2((java.lang.String)v);
            break;
        case 327:
            setTELEBOX((java.lang.String)v);
            break;
        case 328:
            setFAX_NUMBER((java.lang.String)v);
            break;
        case 329:
            setTELETEX_NO((java.lang.String)v);
            break;
        case 330:
            setTELEX_NO((java.lang.String)v);
            break;
        case 331:
            setLANGU((java.lang.String)v);
            break;
        case 332:
            setLANGU_ISO((java.lang.String)v);
            break;
        case 333:
            setUNLOAD_PT((java.lang.String)v);
            break;
        case 334:
            setTRANSPZONE((java.lang.String)v);
            break;
        case 335:
            setTAXJURCODE((java.lang.String)v);
            break;
        case 336:
            setADDRESS((java.lang.String)v);
            break;
        case 337:
            setPRIV_ADDR((java.lang.String)v);
            break;
        case 338:
            setADDR_TYPE((java.lang.String)v);
            break;
        case 339:
            setADDR_ORIG((java.lang.String)v);
            break;
        case 340:
            setADDR_LINK((java.lang.String)v);
            break;
        case 341:
            setREFOBJTYPE((java.lang.String)v);
            break;
        case 342:
            setREFOBJKEY((java.lang.String)v);
            break;
        case 343:
            setREFLOGSYS((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of PARTN_ROLE  
     */
    public java.lang.String getPARTN_ROLE()
    {
        
        return __PARTN_ROLE;
    }
    
    /**
     * Set the value of PARTN_ROLE  
     */
    public void setPARTN_ROLE(java.lang.String value)
    {
        __PARTN_ROLE = value;
    }
    
    /**
     * get the value of PARTN_NUMB  
     */
    public java.lang.String getPARTN_NUMB()
    {
        
        return __PARTN_NUMB;
    }
    
    /**
     * Set the value of PARTN_NUMB  
     */
    public void setPARTN_NUMB(java.lang.String value)
    {
        __PARTN_NUMB = value;
    }
    
    /**
     * get the value of ITM_NUMBER  
     */
    public java.lang.String getITM_NUMBER()
    {
        
        return __ITM_NUMBER;
    }
    
    /**
     * Set the value of ITM_NUMBER  
     */
    public void setITM_NUMBER(java.lang.String value)
    {
        __ITM_NUMBER = value;
    }
    
    /**
     * get the value of TITLE  
     */
    public java.lang.String getTITLE()
    {
        
        return __TITLE;
    }
    
    /**
     * Set the value of TITLE  
     */
    public void setTITLE(java.lang.String value)
    {
        __TITLE = value;
    }
    
    /**
     * get the value of NAME  
     */
    public java.lang.String getNAME()
    {
        
        return __NAME;
    }
    
    /**
     * Set the value of NAME  
     */
    public void setNAME(java.lang.String value)
    {
        __NAME = value;
    }
    
    /**
     * get the value of NAME_2  
     */
    public java.lang.String getNAME_2()
    {
        
        return __NAME_2;
    }
    
    /**
     * Set the value of NAME_2  
     */
    public void setNAME_2(java.lang.String value)
    {
        __NAME_2 = value;
    }
    
    /**
     * get the value of NAME_3  
     */
    public java.lang.String getNAME_3()
    {
        
        return __NAME_3;
    }
    
    /**
     * Set the value of NAME_3  
     */
    public void setNAME_3(java.lang.String value)
    {
        __NAME_3 = value;
    }
    
    /**
     * get the value of NAME_4  
     */
    public java.lang.String getNAME_4()
    {
        
        return __NAME_4;
    }
    
    /**
     * Set the value of NAME_4  
     */
    public void setNAME_4(java.lang.String value)
    {
        __NAME_4 = value;
    }
    
    /**
     * get the value of STREET  
     */
    public java.lang.String getSTREET()
    {
        
        return __STREET;
    }
    
    /**
     * Set the value of STREET  
     */
    public void setSTREET(java.lang.String value)
    {
        __STREET = value;
    }
    
    /**
     * get the value of COUNTRY  
     */
    public java.lang.String getCOUNTRY()
    {
        
        return __COUNTRY;
    }
    
    /**
     * Set the value of COUNTRY  
     */
    public void setCOUNTRY(java.lang.String value)
    {
        __COUNTRY = value;
    }
    
    /**
     * get the value of COUNTR_ISO  
     */
    public java.lang.String getCOUNTR_ISO()
    {
        
        return __COUNTR_ISO;
    }
    
    /**
     * Set the value of COUNTR_ISO  
     */
    public void setCOUNTR_ISO(java.lang.String value)
    {
        __COUNTR_ISO = value;
    }
    
    /**
     * get the value of POSTL_CODE  
     */
    public java.lang.String getPOSTL_CODE()
    {
        
        return __POSTL_CODE;
    }
    
    /**
     * Set the value of POSTL_CODE  
     */
    public void setPOSTL_CODE(java.lang.String value)
    {
        __POSTL_CODE = value;
    }
    
    /**
     * get the value of POBX_PCD  
     */
    public java.lang.String getPOBX_PCD()
    {
        
        return __POBX_PCD;
    }
    
    /**
     * Set the value of POBX_PCD  
     */
    public void setPOBX_PCD(java.lang.String value)
    {
        __POBX_PCD = value;
    }
    
    /**
     * get the value of POBX_CTY  
     */
    public java.lang.String getPOBX_CTY()
    {
        
        return __POBX_CTY;
    }
    
    /**
     * Set the value of POBX_CTY  
     */
    public void setPOBX_CTY(java.lang.String value)
    {
        __POBX_CTY = value;
    }
    
    /**
     * get the value of CITY  
     */
    public java.lang.String getCITY()
    {
        
        return __CITY;
    }
    
    /**
     * Set the value of CITY  
     */
    public void setCITY(java.lang.String value)
    {
        __CITY = value;
    }
    
    /**
     * get the value of DISTRICT  
     */
    public java.lang.String getDISTRICT()
    {
        
        return __DISTRICT;
    }
    
    /**
     * Set the value of DISTRICT  
     */
    public void setDISTRICT(java.lang.String value)
    {
        __DISTRICT = value;
    }
    
    /**
     * get the value of REGION  
     */
    public java.lang.String getREGION()
    {
        
        return __REGION;
    }
    
    /**
     * Set the value of REGION  
     */
    public void setREGION(java.lang.String value)
    {
        __REGION = value;
    }
    
    /**
     * get the value of PO_BOX  
     */
    public java.lang.String getPO_BOX()
    {
        
        return __PO_BOX;
    }
    
    /**
     * Set the value of PO_BOX  
     */
    public void setPO_BOX(java.lang.String value)
    {
        __PO_BOX = value;
    }
    
    /**
     * get the value of TELEPHONE  
     */
    public java.lang.String getTELEPHONE()
    {
        
        return __TELEPHONE;
    }
    
    /**
     * Set the value of TELEPHONE  
     */
    public void setTELEPHONE(java.lang.String value)
    {
        __TELEPHONE = value;
    }
    
    /**
     * get the value of TELEPHONE2  
     */
    public java.lang.String getTELEPHONE2()
    {
        
        return __TELEPHONE2;
    }
    
    /**
     * Set the value of TELEPHONE2  
     */
    public void setTELEPHONE2(java.lang.String value)
    {
        __TELEPHONE2 = value;
    }
    
    /**
     * get the value of TELEBOX  
     */
    public java.lang.String getTELEBOX()
    {
        
        return __TELEBOX;
    }
    
    /**
     * Set the value of TELEBOX  
     */
    public void setTELEBOX(java.lang.String value)
    {
        __TELEBOX = value;
    }
    
    /**
     * get the value of FAX_NUMBER  
     */
    public java.lang.String getFAX_NUMBER()
    {
        
        return __FAX_NUMBER;
    }
    
    /**
     * Set the value of FAX_NUMBER  
     */
    public void setFAX_NUMBER(java.lang.String value)
    {
        __FAX_NUMBER = value;
    }
    
    /**
     * get the value of TELETEX_NO  
     */
    public java.lang.String getTELETEX_NO()
    {
        
        return __TELETEX_NO;
    }
    
    /**
     * Set the value of TELETEX_NO  
     */
    public void setTELETEX_NO(java.lang.String value)
    {
        __TELETEX_NO = value;
    }
    
    /**
     * get the value of TELEX_NO  
     */
    public java.lang.String getTELEX_NO()
    {
        
        return __TELEX_NO;
    }
    
    /**
     * Set the value of TELEX_NO  
     */
    public void setTELEX_NO(java.lang.String value)
    {
        __TELEX_NO = value;
    }
    
    /**
     * get the value of LANGU  
     */
    public java.lang.String getLANGU()
    {
        
        return __LANGU;
    }
    
    /**
     * Set the value of LANGU  
     */
    public void setLANGU(java.lang.String value)
    {
        __LANGU = value;
    }
    
    /**
     * get the value of LANGU_ISO  
     */
    public java.lang.String getLANGU_ISO()
    {
        
        return __LANGU_ISO;
    }
    
    /**
     * Set the value of LANGU_ISO  
     */
    public void setLANGU_ISO(java.lang.String value)
    {
        __LANGU_ISO = value;
    }
    
    /**
     * get the value of UNLOAD_PT  
     */
    public java.lang.String getUNLOAD_PT()
    {
        
        return __UNLOAD_PT;
    }
    
    /**
     * Set the value of UNLOAD_PT  
     */
    public void setUNLOAD_PT(java.lang.String value)
    {
        __UNLOAD_PT = value;
    }
    
    /**
     * get the value of TRANSPZONE  
     */
    public java.lang.String getTRANSPZONE()
    {
        
        return __TRANSPZONE;
    }
    
    /**
     * Set the value of TRANSPZONE  
     */
    public void setTRANSPZONE(java.lang.String value)
    {
        __TRANSPZONE = value;
    }
    
    /**
     * get the value of TAXJURCODE  
     */
    public java.lang.String getTAXJURCODE()
    {
        
        return __TAXJURCODE;
    }
    
    /**
     * Set the value of TAXJURCODE  
     */
    public void setTAXJURCODE(java.lang.String value)
    {
        __TAXJURCODE = value;
    }
    
    /**
     * get the value of ADDRESS  
     */
    public java.lang.String getADDRESS()
    {
        
        return __ADDRESS;
    }
    
    /**
     * Set the value of ADDRESS  
     */
    public void setADDRESS(java.lang.String value)
    {
        __ADDRESS = value;
    }
    
    /**
     * get the value of PRIV_ADDR  
     */
    public java.lang.String getPRIV_ADDR()
    {
        
        return __PRIV_ADDR;
    }
    
    /**
     * Set the value of PRIV_ADDR  
     */
    public void setPRIV_ADDR(java.lang.String value)
    {
        __PRIV_ADDR = value;
    }
    
    /**
     * get the value of ADDR_TYPE  
     */
    public java.lang.String getADDR_TYPE()
    {
        
        return __ADDR_TYPE;
    }
    
    /**
     * Set the value of ADDR_TYPE  
     */
    public void setADDR_TYPE(java.lang.String value)
    {
        __ADDR_TYPE = value;
    }
    
    /**
     * get the value of ADDR_ORIG  
     */
    public java.lang.String getADDR_ORIG()
    {
        
        return __ADDR_ORIG;
    }
    
    /**
     * Set the value of ADDR_ORIG  
     */
    public void setADDR_ORIG(java.lang.String value)
    {
        __ADDR_ORIG = value;
    }
    
    /**
     * get the value of ADDR_LINK  
     */
    public java.lang.String getADDR_LINK()
    {
        
        return __ADDR_LINK;
    }
    
    /**
     * Set the value of ADDR_LINK  
     */
    public void setADDR_LINK(java.lang.String value)
    {
        __ADDR_LINK = value;
    }
    
    /**
     * get the value of REFOBJTYPE  
     */
    public java.lang.String getREFOBJTYPE()
    {
        
        return __REFOBJTYPE;
    }
    
    /**
     * Set the value of REFOBJTYPE  
     */
    public void setREFOBJTYPE(java.lang.String value)
    {
        __REFOBJTYPE = value;
    }
    
    /**
     * get the value of REFOBJKEY  
     */
    public java.lang.String getREFOBJKEY()
    {
        
        return __REFOBJKEY;
    }
    
    /**
     * Set the value of REFOBJKEY  
     */
    public void setREFOBJKEY(java.lang.String value)
    {
        __REFOBJKEY = value;
    }
    
    /**
     * get the value of REFLOGSYS  
     */
    public java.lang.String getREFLOGSYS()
    {
        
        return __REFLOGSYS;
    }
    
    /**
     * Set the value of REFLOGSYS  
     */
    public void setREFLOGSYS(java.lang.String value)
    {
        __REFLOGSYS = value;
    }
}