/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class KeyGeneratorPK extends com.sybase.persistence.AbstractStructure implements com.sybase.reflection.ClassWithMetaData
{
    private static GBI_SalesApp.intrnl.KeyGeneratorPKMetaData META_DATA = new GBI_SalesApp.intrnl.KeyGeneratorPKMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("KeyGeneratorPK", GBI_SalesApp.KeyGeneratorPK.class, META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
    
    /**
     * Creates an instance of GBI_SalesApp.KeyGeneratorPK  
     */
    public KeyGeneratorPK()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    
    private java.lang.String __remoteId ;  
    
    private long __batchId ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 575:
            return getBatchId();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 575:
            setBatchId((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 574:
            return getRemoteId();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 574:
            setRemoteId((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of remoteId  
     */
    public java.lang.String getRemoteId()
    {
        
        return __remoteId;
    }
    
    /**
     * Set the value of remoteId  
     */
    public void setRemoteId(java.lang.String value)
    {
        __remoteId = value;
    }
    
    /**
     * get the value of batchId  
     */
    public long getBatchId()
    {
        
        return __batchId;
    }
    
    /**
     * Set the value of batchId  
     */
    public void setBatchId(long value)
    {
        __batchId = value;
    }
}