/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class OfflineAuthentication extends com.sybase.persistence.AbstractLocalEntity implements com.sybase.persistence.LocalBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static GBI_SalesApp.intrnl.OfflineAuthenticationMetaData META_DATA = new GBI_SalesApp.intrnl.OfflineAuthenticationMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("OfflineAuthentication", GBI_SalesApp.OfflineAuthentication.class, "GBI_SalesApp.OfflineAuthentication", META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private int __passwordHash ;  
    
    private java.lang.String __user ;  
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 522:
            return getUser();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 522:
            setUser((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public int getAttributeInt(int id)
    {
        switch(id)
        {
        case 523:
            return getPasswordHash();
        default:
            return super.getAttributeInt(id);
        }
    }
    
    public void setAttributeInt(int id, int v)
    {
        switch(id)
        {
        case 523:
            setPasswordHash((int)v);
            break;
        default:
            super.setAttributeInt(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of GBI_SalesApp.OfflineAuthentication  
     */
    public OfflineAuthentication()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of passwordHash  
     */
    public int getPasswordHash()
    {
        
        return __passwordHash;
    }
    
    /**
     * Set the value of passwordHash  
     */
    public void setPasswordHash(int value)
    {
        if(__passwordHash != value)
        {
            _isDirty = true;
        }
        __passwordHash = value;
    }       
    /**
     * get the value of user  
     */
    public java.lang.String getUser()
    {
        
        return __user;
    }
    
    /**
     * Set the value of user  
     */
    public void setUser(java.lang.String value)
    {
        if ((__user == null) != (value == null) || (value != null && ! value.equals(__user)))
        {
            _isDirty = true;
        }
        __user = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static GBI_SalesApp.OfflineAuthentication find(java.lang.String id)
    {
        Object[] keys = new Object[]{id};
        return (GBI_SalesApp.OfflineAuthentication)(DELEGATE.findEntityWithKeys(keys));
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static GBI_SalesApp.OfflineAuthentication load(java.lang.String id)
    {
        return (GBI_SalesApp.OfflineAuthentication)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.String _pk()
    {
        return (java.lang.String)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.OfflineAuthentication> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<GBI_SalesApp.OfflineAuthentication>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.OfflineAuthentication> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<GBI_SalesApp.OfflineAuthentication>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
}