/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class SalesOrderGetStatus extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static GBI_SalesApp.intrnl.SalesOrderGetStatusMetaData META_DATA = new GBI_SalesApp.intrnl.SalesOrderGetStatusMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("SalesOrderGetStatus", GBI_SalesApp.SalesOrderGetStatus.class, "GBI_SalesApp.SalesOrderGetStatus", META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __DOC_NUMBER ;  
    
    private java.lang.String __PURCH_NO ;  
    
    private java.lang.String __PRC_STAT_H ;  
    
    private java.lang.String __DLV_STAT_H ;  
    
    private java.lang.String __DLV_BLOCK ;  
    
    private java.lang.String __ITM_NUMBER ;  
    
    private java.lang.String __MATERIAL ;  
    
    private java.lang.String __SHORT_TEXT ;  
    
    private java.math.BigDecimal __REQ_QTY ;  
    
    private java.math.BigDecimal __CUM_CF_QTY ;  
    
    private java.lang.String __SALES_UNIT ;  
    
    private java.math.BigDecimal __NET_VALUE ;  
    
    private java.lang.String __CURRENCY ;  
    
    private java.math.BigDecimal __NET_PRICE ;  
    
    private java.math.BigDecimal __COND_P_UNT ;  
    
    private java.lang.String __COND_UNIT ;  
    
    private java.lang.String __DLV_STAT_I ;  
    
    private java.lang.String __DELIV_NUMB ;  
    
    private java.lang.String __DELIV_ITEM ;  
    
    private java.math.BigDecimal __DLV_QTY ;  
    
    private java.math.BigDecimal __REF_QTY ;  
    
    private java.lang.String __S_UNIT_ISO ;  
    
    private java.lang.String __CD_UNT_ISO ;  
    
    private java.lang.String __CURR_ISO ;  
    
    private java.lang.String __MATERIAL_EXTERNAL ;  
    
    private java.lang.String __MATERIAL_GUID ;  
    
    private java.lang.String __MATERIAL_VERSION ;  
    
    private java.lang.String __PO_ITM_NO ;  
    
    private java.lang.String __S_UNIT_DLV ;  
    
    private java.lang.String __DLV_UNIT_ISO ;  
    
    private java.lang.String __REA_FOR_RE ;  
    
    private java.lang.String __PURCH_NO_C ;  
    
      
    
      
    
      
    
      
    
    private long __surrogateKey ;  
    
      
    
      
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 464:
            return getSurrogateKey();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 464:
            setSurrogateKey((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public java.math.BigDecimal getAttributeDecimal(int id)
    {
        switch(id)
        {
        case 440:
            return getREQ_QTY();
        case 441:
            return getCUM_CF_QTY();
        case 443:
            return getNET_VALUE();
        case 445:
            return getNET_PRICE();
        case 446:
            return getCOND_P_UNT();
        case 451:
            return getDLV_QTY();
        case 452:
            return getREF_QTY();
        default:
            return super.getAttributeDecimal(id);
        }
    }
    
    public void setAttributeDecimal(int id, java.math.BigDecimal v)
    {
        switch(id)
        {
        case 440:
            setREQ_QTY((java.math.BigDecimal)v);
            break;
        case 441:
            setCUM_CF_QTY((java.math.BigDecimal)v);
            break;
        case 443:
            setNET_VALUE((java.math.BigDecimal)v);
            break;
        case 445:
            setNET_PRICE((java.math.BigDecimal)v);
            break;
        case 446:
            setCOND_P_UNT((java.math.BigDecimal)v);
            break;
        case 451:
            setDLV_QTY((java.math.BigDecimal)v);
            break;
        case 452:
            setREF_QTY((java.math.BigDecimal)v);
            break;
        default:
            super.setAttributeDecimal(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 432:
            return getDOC_NUMBER();
        case 433:
            return getPURCH_NO();
        case 434:
            return getPRC_STAT_H();
        case 435:
            return getDLV_STAT_H();
        case 436:
            return getDLV_BLOCK();
        case 437:
            return getITM_NUMBER();
        case 438:
            return getMATERIAL();
        case 439:
            return getSHORT_TEXT();
        case 442:
            return getSALES_UNIT();
        case 444:
            return getCURRENCY();
        case 447:
            return getCOND_UNIT();
        case 448:
            return getDLV_STAT_I();
        case 449:
            return getDELIV_NUMB();
        case 450:
            return getDELIV_ITEM();
        case 453:
            return getS_UNIT_ISO();
        case 454:
            return getCD_UNT_ISO();
        case 455:
            return getCURR_ISO();
        case 456:
            return getMATERIAL_EXTERNAL();
        case 457:
            return getMATERIAL_GUID();
        case 458:
            return getMATERIAL_VERSION();
        case 459:
            return getPO_ITM_NO();
        case 460:
            return getS_UNIT_DLV();
        case 461:
            return getDLV_UNIT_ISO();
        case 462:
            return getREA_FOR_RE();
        case 463:
            return getPURCH_NO_C();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 432:
            setDOC_NUMBER((java.lang.String)v);
            break;
        case 433:
            setPURCH_NO((java.lang.String)v);
            break;
        case 434:
            setPRC_STAT_H((java.lang.String)v);
            break;
        case 435:
            setDLV_STAT_H((java.lang.String)v);
            break;
        case 436:
            setDLV_BLOCK((java.lang.String)v);
            break;
        case 437:
            setITM_NUMBER((java.lang.String)v);
            break;
        case 438:
            setMATERIAL((java.lang.String)v);
            break;
        case 439:
            setSHORT_TEXT((java.lang.String)v);
            break;
        case 442:
            setSALES_UNIT((java.lang.String)v);
            break;
        case 444:
            setCURRENCY((java.lang.String)v);
            break;
        case 447:
            setCOND_UNIT((java.lang.String)v);
            break;
        case 448:
            setDLV_STAT_I((java.lang.String)v);
            break;
        case 449:
            setDELIV_NUMB((java.lang.String)v);
            break;
        case 450:
            setDELIV_ITEM((java.lang.String)v);
            break;
        case 453:
            setS_UNIT_ISO((java.lang.String)v);
            break;
        case 454:
            setCD_UNT_ISO((java.lang.String)v);
            break;
        case 455:
            setCURR_ISO((java.lang.String)v);
            break;
        case 456:
            setMATERIAL_EXTERNAL((java.lang.String)v);
            break;
        case 457:
            setMATERIAL_GUID((java.lang.String)v);
            break;
        case 458:
            setMATERIAL_VERSION((java.lang.String)v);
            break;
        case 459:
            setPO_ITM_NO((java.lang.String)v);
            break;
        case 460:
            setS_UNIT_DLV((java.lang.String)v);
            break;
        case 461:
            setDLV_UNIT_ISO((java.lang.String)v);
            break;
        case 462:
            setREA_FOR_RE((java.lang.String)v);
            break;
        case 463:
            setPURCH_NO_C((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of GBI_SalesApp.SalesOrderGetStatus  
     */
    public SalesOrderGetStatus()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of DOC_NUMBER  
     */
    public java.lang.String getDOC_NUMBER()
    {
        
        return __DOC_NUMBER;
    }
    
    /**
     * Set the value of DOC_NUMBER  
     */
    public void setDOC_NUMBER(java.lang.String value)
    {
        if ((__DOC_NUMBER == null) != (value == null) || (value != null && ! value.equals(__DOC_NUMBER)))
        {
            _isDirty = true;
        }
        __DOC_NUMBER = value;
    }       
    /**
     * get the value of PURCH_NO  
     */
    public java.lang.String getPURCH_NO()
    {
        
        return __PURCH_NO;
    }
    
    /**
     * Set the value of PURCH_NO  
     */
    public void setPURCH_NO(java.lang.String value)
    {
        if ((__PURCH_NO == null) != (value == null) || (value != null && ! value.equals(__PURCH_NO)))
        {
            _isDirty = true;
        }
        __PURCH_NO = value;
    }       
    /**
     * get the value of PRC_STAT_H  
     */
    public java.lang.String getPRC_STAT_H()
    {
        
        return __PRC_STAT_H;
    }
    
    /**
     * Set the value of PRC_STAT_H  
     */
    public void setPRC_STAT_H(java.lang.String value)
    {
        if ((__PRC_STAT_H == null) != (value == null) || (value != null && ! value.equals(__PRC_STAT_H)))
        {
            _isDirty = true;
        }
        __PRC_STAT_H = value;
    }       
    /**
     * get the value of DLV_STAT_H  
     */
    public java.lang.String getDLV_STAT_H()
    {
        
        return __DLV_STAT_H;
    }
    
    /**
     * Set the value of DLV_STAT_H  
     */
    public void setDLV_STAT_H(java.lang.String value)
    {
        if ((__DLV_STAT_H == null) != (value == null) || (value != null && ! value.equals(__DLV_STAT_H)))
        {
            _isDirty = true;
        }
        __DLV_STAT_H = value;
    }       
    /**
     * get the value of DLV_BLOCK  
     */
    public java.lang.String getDLV_BLOCK()
    {
        
        return __DLV_BLOCK;
    }
    
    /**
     * Set the value of DLV_BLOCK  
     */
    public void setDLV_BLOCK(java.lang.String value)
    {
        if ((__DLV_BLOCK == null) != (value == null) || (value != null && ! value.equals(__DLV_BLOCK)))
        {
            _isDirty = true;
        }
        __DLV_BLOCK = value;
    }       
    /**
     * get the value of ITM_NUMBER  
     */
    public java.lang.String getITM_NUMBER()
    {
        
        return __ITM_NUMBER;
    }
    
    /**
     * Set the value of ITM_NUMBER  
     */
    public void setITM_NUMBER(java.lang.String value)
    {
        if ((__ITM_NUMBER == null) != (value == null) || (value != null && ! value.equals(__ITM_NUMBER)))
        {
            _isDirty = true;
        }
        __ITM_NUMBER = value;
    }       
    /**
     * get the value of MATERIAL  
     */
    public java.lang.String getMATERIAL()
    {
        
        return __MATERIAL;
    }
    
    /**
     * Set the value of MATERIAL  
     */
    public void setMATERIAL(java.lang.String value)
    {
        if ((__MATERIAL == null) != (value == null) || (value != null && ! value.equals(__MATERIAL)))
        {
            _isDirty = true;
        }
        __MATERIAL = value;
    }       
    /**
     * get the value of SHORT_TEXT  
     */
    public java.lang.String getSHORT_TEXT()
    {
        
        return __SHORT_TEXT;
    }
    
    /**
     * Set the value of SHORT_TEXT  
     */
    public void setSHORT_TEXT(java.lang.String value)
    {
        if ((__SHORT_TEXT == null) != (value == null) || (value != null && ! value.equals(__SHORT_TEXT)))
        {
            _isDirty = true;
        }
        __SHORT_TEXT = value;
    }       
    /**
     * get the value of REQ_QTY  
     */
    public java.math.BigDecimal getREQ_QTY()
    {
        
        return __REQ_QTY;
    }
    
    /**
     * Set the value of REQ_QTY  
     */
    public void setREQ_QTY(java.math.BigDecimal value)
    {
        if ((__REQ_QTY == null) != (value == null) || (value != null && ! value.equals(__REQ_QTY)))
        {
            _isDirty = true;
        }
        __REQ_QTY = value;
    }       
    /**
     * get the value of CUM_CF_QTY  
     */
    public java.math.BigDecimal getCUM_CF_QTY()
    {
        
        return __CUM_CF_QTY;
    }
    
    /**
     * Set the value of CUM_CF_QTY  
     */
    public void setCUM_CF_QTY(java.math.BigDecimal value)
    {
        if ((__CUM_CF_QTY == null) != (value == null) || (value != null && ! value.equals(__CUM_CF_QTY)))
        {
            _isDirty = true;
        }
        __CUM_CF_QTY = value;
    }       
    /**
     * get the value of SALES_UNIT  
     */
    public java.lang.String getSALES_UNIT()
    {
        
        return __SALES_UNIT;
    }
    
    /**
     * Set the value of SALES_UNIT  
     */
    public void setSALES_UNIT(java.lang.String value)
    {
        if ((__SALES_UNIT == null) != (value == null) || (value != null && ! value.equals(__SALES_UNIT)))
        {
            _isDirty = true;
        }
        __SALES_UNIT = value;
    }       
    /**
     * get the value of NET_VALUE  
     */
    public java.math.BigDecimal getNET_VALUE()
    {
        
        return __NET_VALUE;
    }
    
    /**
     * Set the value of NET_VALUE  
     */
    public void setNET_VALUE(java.math.BigDecimal value)
    {
        if ((__NET_VALUE == null) != (value == null) || (value != null && ! value.equals(__NET_VALUE)))
        {
            _isDirty = true;
        }
        __NET_VALUE = value;
    }       
    /**
     * get the value of CURRENCY  
     */
    public java.lang.String getCURRENCY()
    {
        
        return __CURRENCY;
    }
    
    /**
     * Set the value of CURRENCY  
     */
    public void setCURRENCY(java.lang.String value)
    {
        if ((__CURRENCY == null) != (value == null) || (value != null && ! value.equals(__CURRENCY)))
        {
            _isDirty = true;
        }
        __CURRENCY = value;
    }       
    /**
     * get the value of NET_PRICE  
     */
    public java.math.BigDecimal getNET_PRICE()
    {
        
        return __NET_PRICE;
    }
    
    /**
     * Set the value of NET_PRICE  
     */
    public void setNET_PRICE(java.math.BigDecimal value)
    {
        if ((__NET_PRICE == null) != (value == null) || (value != null && ! value.equals(__NET_PRICE)))
        {
            _isDirty = true;
        }
        __NET_PRICE = value;
    }       
    /**
     * get the value of COND_P_UNT  
     */
    public java.math.BigDecimal getCOND_P_UNT()
    {
        
        return __COND_P_UNT;
    }
    
    /**
     * Set the value of COND_P_UNT  
     */
    public void setCOND_P_UNT(java.math.BigDecimal value)
    {
        if ((__COND_P_UNT == null) != (value == null) || (value != null && ! value.equals(__COND_P_UNT)))
        {
            _isDirty = true;
        }
        __COND_P_UNT = value;
    }       
    /**
     * get the value of COND_UNIT  
     */
    public java.lang.String getCOND_UNIT()
    {
        
        return __COND_UNIT;
    }
    
    /**
     * Set the value of COND_UNIT  
     */
    public void setCOND_UNIT(java.lang.String value)
    {
        if ((__COND_UNIT == null) != (value == null) || (value != null && ! value.equals(__COND_UNIT)))
        {
            _isDirty = true;
        }
        __COND_UNIT = value;
    }       
    /**
     * get the value of DLV_STAT_I  
     */
    public java.lang.String getDLV_STAT_I()
    {
        
        return __DLV_STAT_I;
    }
    
    /**
     * Set the value of DLV_STAT_I  
     */
    public void setDLV_STAT_I(java.lang.String value)
    {
        if ((__DLV_STAT_I == null) != (value == null) || (value != null && ! value.equals(__DLV_STAT_I)))
        {
            _isDirty = true;
        }
        __DLV_STAT_I = value;
    }       
    /**
     * get the value of DELIV_NUMB  
     */
    public java.lang.String getDELIV_NUMB()
    {
        
        return __DELIV_NUMB;
    }
    
    /**
     * Set the value of DELIV_NUMB  
     */
    public void setDELIV_NUMB(java.lang.String value)
    {
        if ((__DELIV_NUMB == null) != (value == null) || (value != null && ! value.equals(__DELIV_NUMB)))
        {
            _isDirty = true;
        }
        __DELIV_NUMB = value;
    }       
    /**
     * get the value of DELIV_ITEM  
     */
    public java.lang.String getDELIV_ITEM()
    {
        
        return __DELIV_ITEM;
    }
    
    /**
     * Set the value of DELIV_ITEM  
     */
    public void setDELIV_ITEM(java.lang.String value)
    {
        if ((__DELIV_ITEM == null) != (value == null) || (value != null && ! value.equals(__DELIV_ITEM)))
        {
            _isDirty = true;
        }
        __DELIV_ITEM = value;
    }       
    /**
     * get the value of DLV_QTY  
     */
    public java.math.BigDecimal getDLV_QTY()
    {
        
        return __DLV_QTY;
    }
    
    /**
     * Set the value of DLV_QTY  
     */
    public void setDLV_QTY(java.math.BigDecimal value)
    {
        if ((__DLV_QTY == null) != (value == null) || (value != null && ! value.equals(__DLV_QTY)))
        {
            _isDirty = true;
        }
        __DLV_QTY = value;
    }       
    /**
     * get the value of REF_QTY  
     */
    public java.math.BigDecimal getREF_QTY()
    {
        
        return __REF_QTY;
    }
    
    /**
     * Set the value of REF_QTY  
     */
    public void setREF_QTY(java.math.BigDecimal value)
    {
        if ((__REF_QTY == null) != (value == null) || (value != null && ! value.equals(__REF_QTY)))
        {
            _isDirty = true;
        }
        __REF_QTY = value;
    }       
    /**
     * get the value of S_UNIT_ISO  
     */
    public java.lang.String getS_UNIT_ISO()
    {
        
        return __S_UNIT_ISO;
    }
    
    /**
     * Set the value of S_UNIT_ISO  
     */
    public void setS_UNIT_ISO(java.lang.String value)
    {
        if ((__S_UNIT_ISO == null) != (value == null) || (value != null && ! value.equals(__S_UNIT_ISO)))
        {
            _isDirty = true;
        }
        __S_UNIT_ISO = value;
    }       
    /**
     * get the value of CD_UNT_ISO  
     */
    public java.lang.String getCD_UNT_ISO()
    {
        
        return __CD_UNT_ISO;
    }
    
    /**
     * Set the value of CD_UNT_ISO  
     */
    public void setCD_UNT_ISO(java.lang.String value)
    {
        if ((__CD_UNT_ISO == null) != (value == null) || (value != null && ! value.equals(__CD_UNT_ISO)))
        {
            _isDirty = true;
        }
        __CD_UNT_ISO = value;
    }       
    /**
     * get the value of CURR_ISO  
     */
    public java.lang.String getCURR_ISO()
    {
        
        return __CURR_ISO;
    }
    
    /**
     * Set the value of CURR_ISO  
     */
    public void setCURR_ISO(java.lang.String value)
    {
        if ((__CURR_ISO == null) != (value == null) || (value != null && ! value.equals(__CURR_ISO)))
        {
            _isDirty = true;
        }
        __CURR_ISO = value;
    }       
    /**
     * get the value of MATERIAL_EXTERNAL  
     */
    public java.lang.String getMATERIAL_EXTERNAL()
    {
        
        return __MATERIAL_EXTERNAL;
    }
    
    /**
     * Set the value of MATERIAL_EXTERNAL  
     */
    public void setMATERIAL_EXTERNAL(java.lang.String value)
    {
        if ((__MATERIAL_EXTERNAL == null) != (value == null) || (value != null && ! value.equals(__MATERIAL_EXTERNAL)))
        {
            _isDirty = true;
        }
        __MATERIAL_EXTERNAL = value;
    }       
    /**
     * get the value of MATERIAL_GUID  
     */
    public java.lang.String getMATERIAL_GUID()
    {
        
        return __MATERIAL_GUID;
    }
    
    /**
     * Set the value of MATERIAL_GUID  
     */
    public void setMATERIAL_GUID(java.lang.String value)
    {
        if ((__MATERIAL_GUID == null) != (value == null) || (value != null && ! value.equals(__MATERIAL_GUID)))
        {
            _isDirty = true;
        }
        __MATERIAL_GUID = value;
    }       
    /**
     * get the value of MATERIAL_VERSION  
     */
    public java.lang.String getMATERIAL_VERSION()
    {
        
        return __MATERIAL_VERSION;
    }
    
    /**
     * Set the value of MATERIAL_VERSION  
     */
    public void setMATERIAL_VERSION(java.lang.String value)
    {
        if ((__MATERIAL_VERSION == null) != (value == null) || (value != null && ! value.equals(__MATERIAL_VERSION)))
        {
            _isDirty = true;
        }
        __MATERIAL_VERSION = value;
    }       
    /**
     * get the value of PO_ITM_NO  
     */
    public java.lang.String getPO_ITM_NO()
    {
        
        return __PO_ITM_NO;
    }
    
    /**
     * Set the value of PO_ITM_NO  
     */
    public void setPO_ITM_NO(java.lang.String value)
    {
        if ((__PO_ITM_NO == null) != (value == null) || (value != null && ! value.equals(__PO_ITM_NO)))
        {
            _isDirty = true;
        }
        __PO_ITM_NO = value;
    }       
    /**
     * get the value of S_UNIT_DLV  
     */
    public java.lang.String getS_UNIT_DLV()
    {
        
        return __S_UNIT_DLV;
    }
    
    /**
     * Set the value of S_UNIT_DLV  
     */
    public void setS_UNIT_DLV(java.lang.String value)
    {
        if ((__S_UNIT_DLV == null) != (value == null) || (value != null && ! value.equals(__S_UNIT_DLV)))
        {
            _isDirty = true;
        }
        __S_UNIT_DLV = value;
    }       
    /**
     * get the value of DLV_UNIT_ISO  
     */
    public java.lang.String getDLV_UNIT_ISO()
    {
        
        return __DLV_UNIT_ISO;
    }
    
    /**
     * Set the value of DLV_UNIT_ISO  
     */
    public void setDLV_UNIT_ISO(java.lang.String value)
    {
        if ((__DLV_UNIT_ISO == null) != (value == null) || (value != null && ! value.equals(__DLV_UNIT_ISO)))
        {
            _isDirty = true;
        }
        __DLV_UNIT_ISO = value;
    }       
    /**
     * get the value of REA_FOR_RE  
     */
    public java.lang.String getREA_FOR_RE()
    {
        
        return __REA_FOR_RE;
    }
    
    /**
     * Set the value of REA_FOR_RE  
     */
    public void setREA_FOR_RE(java.lang.String value)
    {
        if ((__REA_FOR_RE == null) != (value == null) || (value != null && ! value.equals(__REA_FOR_RE)))
        {
            _isDirty = true;
        }
        __REA_FOR_RE = value;
    }       
    /**
     * get the value of PURCH_NO_C  
     */
    public java.lang.String getPURCH_NO_C()
    {
        
        return __PURCH_NO_C;
    }
    
    /**
     * Set the value of PURCH_NO_C  
     */
    public void setPURCH_NO_C(java.lang.String value)
    {
        if ((__PURCH_NO_C == null) != (value == null) || (value != null && ! value.equals(__PURCH_NO_C)))
        {
            _isDirty = true;
        }
        __PURCH_NO_C = value;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static GBI_SalesApp.SalesOrderGetStatus find(long id)
    {
        Object[] keys = new Object[]{id};
        return (GBI_SalesApp.SalesOrderGetStatus)(DELEGATE.findEntityWithKeys(keys));
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static GBI_SalesApp.SalesOrderGetStatus load(long id)
    {
        return (GBI_SalesApp.SalesOrderGetStatus)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of SalesOrderGetStatus
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus>)(Object)DELEGATE.findWithQuery(query, GBI_SalesApp.SalesOrderGetStatus.class);
    }
    
    /**
     * Find a List of GBI_SalesApp.SalesOrderGetStatus
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus> findAll(int skip, int take)
    {
        String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"bh\",x.\"_rc\",x.\"_ds\" FROM \"gbi_s"
                                            + "alesapp_1_0_salesordergetstatus\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"bh\" from \"gbi_salesapp_1_0_salesordergetstatus_os\" x_os where x_os.\"bh\" = x.\"bh\"))))"; 
        return (com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, GBI_SalesApp.SalesOrderGetStatus.class);
    }
    /**
     * Find a list of GBI_SalesApp.SalesOrderGetStatus  
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object GBI_SalesApp.SalesOrderGetStatus
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static GBI_SalesApp.SalesOrderGetStatus findOrderStatus(java.lang.String DocNum)
    {
        
        
            String _selectSQL = "SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"bh\",x.\"_rc\",x.\"_ds\" FROM "
                                    + "\"gbi_salesapp_1_0_salesordergetstatus\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"bh\" from \"gbi_salesapp_1_0_salesordergetstatus_os\" x_os where x_os.\"bh\" = x.\"bh\")))) and ( x.\"a\" = ?)";
            String[] ids = new String[0];
            com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                com.sybase.reflection.DataType.forName("string"),
            };
            Object[] values = new Object[] { 
                DocNum,
            };
            Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, GBI_SalesApp.SalesOrderGetStatus.class);
            return (GBI_SalesApp.SalesOrderGetStatus)res;
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<GBI_SalesApp.SalesOrderGetStatus>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return GBI_SalesApp.LogRecordImpl.findByEntity("SalesOrderGetStatus", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException();
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException();
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException();
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public GBI_SalesApp.SalesOrderGetStatus getDownloadState()
    {
        return (GBI_SalesApp.SalesOrderGetStatus)i_getDownloadState();
    }
    
    public GBI_SalesApp.SalesOrderGetStatus getOriginalState()
    {
        return (GBI_SalesApp.SalesOrderGetStatus)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}