/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */  
package GBI_SalesApp.intrnl;

public class BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_INMetaData
extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_INMetaData()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getMetaData());
        _init();
    }
    
    protected void _init()
    {
        setId(13);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData REFOBJTYPE_attribute = addAttributeWithParams
        	(0, "REFOBJTYPE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFOBJKEY_attribute = addAttributeWithParams
        	(1, "REFOBJKEY", "string", 
        	70, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(70)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFDOCTYPE_attribute = addAttributeWithParams
        	(2, "REFDOCTYPE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_TYPE_attribute = addAttributeWithParams
        	(3, "DOC_TYPE", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COLLECT_NO_attribute = addAttributeWithParams
        	(4, "COLLECT_NO", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_ORG_attribute = addAttributeWithParams
        	(5, "SALES_ORG", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DISTR_CHAN_attribute = addAttributeWithParams
        	(6, "DISTR_CHAN", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DIVISION_attribute = addAttributeWithParams
        	(7, "DIVISION", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_GRP_attribute = addAttributeWithParams
        	(8, "SALES_GRP", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_OFF_attribute = addAttributeWithParams
        	(9, "SALES_OFF", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQ_DATE_H_attribute = addAttributeWithParams
        	(10, "REQ_DATE_H", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DATE_TYPE_attribute = addAttributeWithParams
        	(11, "DATE_TYPE", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_DATE_attribute = addAttributeWithParams
        	(12, "PURCH_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_METHOD_attribute = addAttributeWithParams
        	(13, "PO_METHOD", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_SUPPLEM_attribute = addAttributeWithParams
        	(14, "PO_SUPPLEM", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_1_attribute = addAttributeWithParams
        	(15, "REF_1", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NAME_attribute = addAttributeWithParams
        	(16, "NAME", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TELEPHONE_attribute = addAttributeWithParams
        	(17, "TELEPHONE", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRICE_GRP_attribute = addAttributeWithParams
        	(18, "PRICE_GRP", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GROUP_attribute = addAttributeWithParams
        	(19, "CUST_GROUP", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_DIST_attribute = addAttributeWithParams
        	(20, "SALES_DIST", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRICE_LIST_attribute = addAttributeWithParams
        	(21, "PRICE_LIST", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INCOTERMS1_attribute = addAttributeWithParams
        	(22, "INCOTERMS1", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INCOTERMS2_attribute = addAttributeWithParams
        	(23, "INCOTERMS2", "string", 
        	28, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(28)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PMNTTRMS_attribute = addAttributeWithParams
        	(24, "PMNTTRMS", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_BLOCK_attribute = addAttributeWithParams
        	(25, "DLV_BLOCK", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_BLOCK_attribute = addAttributeWithParams
        	(26, "BILL_BLOCK", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ORD_REASON_attribute = addAttributeWithParams
        	(27, "ORD_REASON", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COMPL_DLV_attribute = addAttributeWithParams
        	(28, "COMPL_DLV", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRICE_DATE_attribute = addAttributeWithParams
        	(29, "PRICE_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData QT_VALID_F_attribute = addAttributeWithParams
        	(30, "QT_VALID_F", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData QT_VALID_T_attribute = addAttributeWithParams
        	(31, "QT_VALID_T", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CT_VALID_F_attribute = addAttributeWithParams
        	(32, "CT_VALID_F", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CT_VALID_T_attribute = addAttributeWithParams
        	(33, "CT_VALID_T", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GRP1_attribute = addAttributeWithParams
        	(34, "CUST_GRP1", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GRP2_attribute = addAttributeWithParams
        	(35, "CUST_GRP2", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GRP3_attribute = addAttributeWithParams
        	(36, "CUST_GRP3", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GRP4_attribute = addAttributeWithParams
        	(37, "CUST_GRP4", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GRP5_attribute = addAttributeWithParams
        	(38, "CUST_GRP5", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_C_attribute = addAttributeWithParams
        	(39, "PURCH_NO_C", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_S_attribute = addAttributeWithParams
        	(40, "PURCH_NO_S", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_DAT_S_attribute = addAttributeWithParams
        	(41, "PO_DAT_S", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_METH_S_attribute = addAttributeWithParams
        	(42, "PO_METH_S", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_1_S_attribute = addAttributeWithParams
        	(43, "REF_1_S", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SD_DOC_CAT_attribute = addAttributeWithParams
        	(44, "SD_DOC_CAT", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_DATE_attribute = addAttributeWithParams
        	(45, "DOC_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData WAR_DATE_attribute = addAttributeWithParams
        	(46, "WAR_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHIP_COND_attribute = addAttributeWithParams
        	(47, "SHIP_COND", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PP_SEARCH_attribute = addAttributeWithParams
        	(48, "PP_SEARCH", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DUN_COUNT_attribute = addAttributeWithParams
        	(49, "DUN_COUNT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(2,0)", "", 2, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DUN_DATE_attribute = addAttributeWithParams
        	(50, "DUN_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLVSCHDUSE_attribute = addAttributeWithParams
        	(51, "DLVSCHDUSE", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PLDLVSTYP_attribute = addAttributeWithParams
        	(52, "PLDLVSTYP", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_DOC_attribute = addAttributeWithParams
        	(53, "REF_DOC", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COMP_CDE_B_attribute = addAttributeWithParams
        	(54, "COMP_CDE_B", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ALTTAX_CLS_attribute = addAttributeWithParams
        	(55, "ALTTAX_CLS", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS2_attribute = addAttributeWithParams
        	(56, "TAX_CLASS2", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS3_attribute = addAttributeWithParams
        	(57, "TAX_CLASS3", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS4_attribute = addAttributeWithParams
        	(58, "TAX_CLASS4", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS5_attribute = addAttributeWithParams
        	(59, "TAX_CLASS5", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS6_attribute = addAttributeWithParams
        	(60, "TAX_CLASS6", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS7_attribute = addAttributeWithParams
        	(61, "TAX_CLASS7", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS8_attribute = addAttributeWithParams
        	(62, "TAX_CLASS8", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS9_attribute = addAttributeWithParams
        	(63, "TAX_CLASS9", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_DOC_L_attribute = addAttributeWithParams
        	(64, "REF_DOC_L", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ASS_NUMBER_attribute = addAttributeWithParams
        	(65, "ASS_NUMBER", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFDOC_CAT_attribute = addAttributeWithParams
        	(66, "REFDOC_CAT", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ORDCOMB_IN_attribute = addAttributeWithParams
        	(67, "ORDCOMB_IN", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_SCHED_attribute = addAttributeWithParams
        	(68, "BILL_SCHED", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INVO_SCHED_attribute = addAttributeWithParams
        	(69, "INVO_SCHED", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MN_INVOICE_attribute = addAttributeWithParams
        	(70, "MN_INVOICE", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXRATE_FI_attribute = addAttributeWithParams
        	(71, "EXRATE_FI", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADD_VAL_DY_attribute = addAttributeWithParams
        	(72, "ADD_VAL_DY", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FIX_VAL_DY_attribute = addAttributeWithParams
        	(73, "FIX_VAL_DY", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PYMT_METH_attribute = addAttributeWithParams
        	(74, "PYMT_METH", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ACCNT_ASGN_attribute = addAttributeWithParams
        	(75, "ACCNT_ASGN", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCHG_RATE_attribute = addAttributeWithParams
        	(76, "EXCHG_RATE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_DATE_attribute = addAttributeWithParams
        	(77, "BILL_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SERV_DATE_attribute = addAttributeWithParams
        	(78, "SERV_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DUNN_KEY_attribute = addAttributeWithParams
        	(79, "DUNN_KEY", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DUNN_BLOCK_attribute = addAttributeWithParams
        	(80, "DUNN_BLOCK", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PMTGAR_PRO_attribute = addAttributeWithParams
        	(81, "PMTGAR_PRO", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DEPARTM_NO_attribute = addAttributeWithParams
        	(82, "DEPARTM_NO", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REC_POINT_attribute = addAttributeWithParams
        	(83, "REC_POINT", "string", 
        	25, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(25)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_NUM_FI_attribute = addAttributeWithParams
        	(84, "DOC_NUM_FI", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP1_attribute = addAttributeWithParams
        	(85, "CSTCNDGRP1", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP2_attribute = addAttributeWithParams
        	(86, "CSTCNDGRP2", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP3_attribute = addAttributeWithParams
        	(87, "CSTCNDGRP3", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP4_attribute = addAttributeWithParams
        	(88, "CSTCNDGRP4", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP5_attribute = addAttributeWithParams
        	(89, "CSTCNDGRP5", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_TIME_attribute = addAttributeWithParams
        	(90, "DLV_TIME", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURRENCY_attribute = addAttributeWithParams
        	(91, "CURRENCY", "string", 
        	5, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(5)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURR_ISO_attribute = addAttributeWithParams
        	(92, "CURR_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CREATED_BY_attribute = addAttributeWithParams
        	(93, "CREATED_BY", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXDEP_CTY_attribute = addAttributeWithParams
        	(94, "TAXDEP_CTY", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXDST_CTY_attribute = addAttributeWithParams
        	(95, "TAXDST_CTY", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EUTRI_DEAL_attribute = addAttributeWithParams
        	(96, "EUTRI_DEAL", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAST_CONTR_attribute = addAttributeWithParams
        	(97, "MAST_CONTR", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_PROC_attribute = addAttributeWithParams
        	(98, "REF_PROC", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CHKPRTAUTH_attribute = addAttributeWithParams
        	(99, "CHKPRTAUTH", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CMLQTY_DAT_attribute = addAttributeWithParams
        	(100, "CMLQTY_DAT", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VERSION_attribute = addAttributeWithParams
        	(101, "VERSION", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NOTIF_NO_attribute = addAttributeWithParams
        	(102, "NOTIF_NO", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData WBS_ELEM_attribute = addAttributeWithParams
        	(103, "WBS_ELEM", "string", 
        	24, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCH_RATE_FI_V_attribute = addAttributeWithParams
        	(104, "EXCH_RATE_FI_V", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCHG_RATE_V_attribute = addAttributeWithParams
        	(105, "EXCHG_RATE_V", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FKK_CONACCT_attribute = addAttributeWithParams
        	(106, "FKK_CONACCT", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CAMPAIGN_attribute = addAttributeWithParams
        	(107, "CAMPAIGN", "binary", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varbinary(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_CLASS_attribute = addAttributeWithParams
        	(108, "DOC_CLASS", "string", 
        	9, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(9)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData H_CURR_attribute = addAttributeWithParams
        	(109, "H_CURR", "string", 
        	5, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(5)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData H_CURR_ISO_attribute = addAttributeWithParams
        	(110, "H_CURR_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHIP_TYPE_attribute = addAttributeWithParams
        	(111, "SHIP_TYPE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData S_PROC_IND_attribute = addAttributeWithParams
        	(112, "S_PROC_IND", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_DOC_L_LONG_attribute = addAttributeWithParams
        	(113, "REF_DOC_L_LONG", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LINE_TIME_attribute = addAttributeWithParams
        	(114, "LINE_TIME", "time?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "time", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CALC_MOTIVE_attribute = addAttributeWithParams
        	(115, "CALC_MOTIVE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_IN");
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}