/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */  
package GBI_SalesApp.intrnl;

public class BAPI_SALESORDER_CREATEFROMDAT2_ORDER_ITEMS_INMetaData
extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public BAPI_SALESORDER_CREATEFROMDAT2_ORDER_ITEMS_INMetaData()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getMetaData());
        _init();
    }
    
    protected void _init()
    {
        setId(14);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData ITM_NUMBER_attribute = addAttributeWithParams
        	(116, "ITM_NUMBER", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData HG_LV_ITEM_attribute = addAttributeWithParams
        	(117, "HG_LV_ITEM", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_ITM_NO_attribute = addAttributeWithParams
        	(118, "PO_ITM_NO", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATERIAL_attribute = addAttributeWithParams
        	(119, "MATERIAL", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ALT_TO_ITM_attribute = addAttributeWithParams
        	(120, "ALT_TO_ITM", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_MAT22_attribute = addAttributeWithParams
        	(121, "CUST_MAT22", "string", 
        	22, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(22)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BATCH_attribute = addAttributeWithParams
        	(122, "BATCH", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_GROUP_attribute = addAttributeWithParams
        	(123, "DLV_GROUP", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PART_DLV_attribute = addAttributeWithParams
        	(124, "PART_DLV", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REASON_REJ_attribute = addAttributeWithParams
        	(125, "REASON_REJ", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_BLOCK_attribute = addAttributeWithParams
        	(126, "BILL_BLOCK", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_DATE_attribute = addAttributeWithParams
        	(127, "BILL_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PLANT_attribute = addAttributeWithParams
        	(128, "PLANT", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData STORE_LOC_attribute = addAttributeWithParams
        	(129, "STORE_LOC", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TARGET_QTY_attribute = addAttributeWithParams
        	(130, "TARGET_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(7,0)", "", 7, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TARGET_QU_attribute = addAttributeWithParams
        	(131, "TARGET_QU", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData T_UNIT_ISO_attribute = addAttributeWithParams
        	(132, "T_UNIT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ITEM_CATEG_attribute = addAttributeWithParams
        	(133, "ITEM_CATEG", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHORT_TEXT_attribute = addAttributeWithParams
        	(134, "SHORT_TEXT", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRC_GROUP1_attribute = addAttributeWithParams
        	(135, "PRC_GROUP1", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRC_GROUP2_attribute = addAttributeWithParams
        	(136, "PRC_GROUP2", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRC_GROUP3_attribute = addAttributeWithParams
        	(137, "PRC_GROUP3", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRC_GROUP4_attribute = addAttributeWithParams
        	(138, "PRC_GROUP4", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRC_GROUP5_attribute = addAttributeWithParams
        	(139, "PRC_GROUP5", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PROD_HIERA_attribute = addAttributeWithParams
        	(140, "PROD_HIERA", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATL_GROUP_attribute = addAttributeWithParams
        	(141, "MATL_GROUP", "string", 
        	9, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(9)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_C_attribute = addAttributeWithParams
        	(142, "PURCH_NO_C", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_DATE_attribute = addAttributeWithParams
        	(143, "PURCH_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_METHOD_attribute = addAttributeWithParams
        	(144, "PO_METHOD", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_1_attribute = addAttributeWithParams
        	(145, "REF_1", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_S_attribute = addAttributeWithParams
        	(146, "PURCH_NO_S", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_DAT_S_attribute = addAttributeWithParams
        	(147, "PO_DAT_S", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_METH_S_attribute = addAttributeWithParams
        	(148, "PO_METH_S", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_1_S_attribute = addAttributeWithParams
        	(149, "REF_1_S", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData POITM_NO_S_attribute = addAttributeWithParams
        	(150, "POITM_NO_S", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRICE_GRP_attribute = addAttributeWithParams
        	(151, "PRICE_GRP", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_GROUP_attribute = addAttributeWithParams
        	(152, "CUST_GROUP", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_DIST_attribute = addAttributeWithParams
        	(153, "SALES_DIST", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRICE_LIST_attribute = addAttributeWithParams
        	(154, "PRICE_LIST", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INCOTERMS1_attribute = addAttributeWithParams
        	(155, "INCOTERMS1", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INCOTERMS2_attribute = addAttributeWithParams
        	(156, "INCOTERMS2", "string", 
        	28, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(28)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ORDCOMP_IN_attribute = addAttributeWithParams
        	(157, "ORDCOMP_IN", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_SCHED_attribute = addAttributeWithParams
        	(158, "BILL_SCHED", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INVO_SCHED_attribute = addAttributeWithParams
        	(159, "INVO_SCHED", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MN_INVOICE_attribute = addAttributeWithParams
        	(160, "MN_INVOICE", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EX_RATE_FI_attribute = addAttributeWithParams
        	(161, "EX_RATE_FI", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ADD_VAL_DY_attribute = addAttributeWithParams
        	(162, "ADD_VAL_DY", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FIX_VAL_DY_attribute = addAttributeWithParams
        	(163, "FIX_VAL_DY", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PMNTTRMS_attribute = addAttributeWithParams
        	(164, "PMNTTRMS", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PYMT_METH_attribute = addAttributeWithParams
        	(165, "PYMT_METH", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ACCNT_ASGN_attribute = addAttributeWithParams
        	(166, "ACCNT_ASGN", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCHG_RATE_attribute = addAttributeWithParams
        	(167, "EXCHG_RATE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRICE_DATE_attribute = addAttributeWithParams
        	(168, "PRICE_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SERV_DATE_attribute = addAttributeWithParams
        	(169, "SERV_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DUNN_KEY_attribute = addAttributeWithParams
        	(170, "DUNN_KEY", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DUNN_BLOCK_attribute = addAttributeWithParams
        	(171, "DUNN_BLOCK", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PROMOTION_attribute = addAttributeWithParams
        	(172, "PROMOTION", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PMTGAR_PRO_attribute = addAttributeWithParams
        	(173, "PMTGAR_PRO", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_NUM_FI_attribute = addAttributeWithParams
        	(174, "DOC_NUM_FI", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DEPARTM_NO_attribute = addAttributeWithParams
        	(175, "DEPARTM_NO", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REC_POINT_attribute = addAttributeWithParams
        	(176, "REC_POINT", "string", 
        	25, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(25)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP1_attribute = addAttributeWithParams
        	(177, "CSTCNDGRP1", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP2_attribute = addAttributeWithParams
        	(178, "CSTCNDGRP2", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP3_attribute = addAttributeWithParams
        	(179, "CSTCNDGRP3", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP4_attribute = addAttributeWithParams
        	(180, "CSTCNDGRP4", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTCNDGRP5_attribute = addAttributeWithParams
        	(181, "CSTCNDGRP5", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_TIME_attribute = addAttributeWithParams
        	(182, "DLV_TIME", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_UNIT_attribute = addAttributeWithParams
        	(183, "SALES_UNIT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData S_UNIT_ISO_attribute = addAttributeWithParams
        	(184, "S_UNIT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TRG_QTY_NO_attribute = addAttributeWithParams
        	(185, "TRG_QTY_NO", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(3,0)", "", 3, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TRGQTY_DEN_attribute = addAttributeWithParams
        	(186, "TRGQTY_DEN", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(3,0)", "", 3, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData RNDDLV_QTY_attribute = addAttributeWithParams
        	(187, "RNDDLV_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(7,0)", "", 7, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAXDEVAMNT_attribute = addAttributeWithParams
        	(188, "MAXDEVAMNT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(7,0)", "", 7, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAXDEVPER_attribute = addAttributeWithParams
        	(189, "MAXDEVPER", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(2,0)", "", 2, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAXDEV_DAY_attribute = addAttributeWithParams
        	(190, "MAXDEV_DAY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(2,0)", "", 2, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData USAGE_IND_attribute = addAttributeWithParams
        	(191, "USAGE_IND", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FIXED_QUAN_attribute = addAttributeWithParams
        	(192, "FIXED_QUAN", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UNLMT_DLV_attribute = addAttributeWithParams
        	(193, "UNLMT_DLV", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData OVERDLVTOL_attribute = addAttributeWithParams
        	(194, "OVERDLVTOL", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(2,0)", "", 2, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UNDDLV_TOL_attribute = addAttributeWithParams
        	(195, "UNDDLV_TOL", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(2,0)", "", 2, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DIVISION_attribute = addAttributeWithParams
        	(196, "DIVISION", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALQTYNUM_attribute = addAttributeWithParams
        	(197, "SALQTYNUM", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(3,0)", "", 3, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALQTYDEN_attribute = addAttributeWithParams
        	(198, "SALQTYDEN", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(3,0)", "", 3, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData GROSS_WGHT_attribute = addAttributeWithParams
        	(199, "GROSS_WGHT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(8,0)", "", 8, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NET_WEIGHT_attribute = addAttributeWithParams
        	(200, "NET_WEIGHT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(8,0)", "", 8, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UNTOF_WGHT_attribute = addAttributeWithParams
        	(201, "UNTOF_WGHT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UNOF_WTISO_attribute = addAttributeWithParams
        	(202, "UNOF_WTISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VOLUME_attribute = addAttributeWithParams
        	(203, "VOLUME", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(8,0)", "", 8, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VOLUNIT_attribute = addAttributeWithParams
        	(204, "VOLUNIT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VOLUNITISO_attribute = addAttributeWithParams
        	(205, "VOLUNITISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_PRIO_attribute = addAttributeWithParams
        	(206, "DLV_PRIO", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHIP_POINT_attribute = addAttributeWithParams
        	(207, "SHIP_POINT", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ROUTE_attribute = addAttributeWithParams
        	(208, "ROUTE", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CREATED_BY_attribute = addAttributeWithParams
        	(209, "CREATED_BY", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS1_attribute = addAttributeWithParams
        	(210, "TAX_CLASS1", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS2_attribute = addAttributeWithParams
        	(211, "TAX_CLASS2", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS3_attribute = addAttributeWithParams
        	(212, "TAX_CLASS3", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS4_attribute = addAttributeWithParams
        	(213, "TAX_CLASS4", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS5_attribute = addAttributeWithParams
        	(214, "TAX_CLASS5", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS6_attribute = addAttributeWithParams
        	(215, "TAX_CLASS6", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS7_attribute = addAttributeWithParams
        	(216, "TAX_CLASS7", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS8_attribute = addAttributeWithParams
        	(217, "TAX_CLASS8", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAX_CLASS9_attribute = addAttributeWithParams
        	(218, "TAX_CLASS9", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_PR_GRP_attribute = addAttributeWithParams
        	(219, "MAT_PR_GRP", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VAL_TYPE_attribute = addAttributeWithParams
        	(220, "VAL_TYPE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FIXDAT_QTY_attribute = addAttributeWithParams
        	(221, "FIXDAT_QTY", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BOMEXPL_NO_attribute = addAttributeWithParams
        	(222, "BOMEXPL_NO", "string", 
        	8, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData RESANALKEY_attribute = addAttributeWithParams
        	(223, "RESANALKEY", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQMTS_TYP_attribute = addAttributeWithParams
        	(224, "REQMTS_TYP", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NO_GR_POST_attribute = addAttributeWithParams
        	(225, "NO_GR_POST", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BUS_TRANST_attribute = addAttributeWithParams
        	(226, "BUS_TRANST", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData OVERHD_KEY_attribute = addAttributeWithParams
        	(227, "OVERHD_KEY", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTG_SHEET_attribute = addAttributeWithParams
        	(228, "CSTG_SHEET", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATFRGTGRP_attribute = addAttributeWithParams
        	(229, "MATFRGTGRP", "string", 
        	8, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PLDLVSHDIN_attribute = addAttributeWithParams
        	(230, "PLDLVSHDIN", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SEQ_NO_attribute = addAttributeWithParams
        	(231, "SEQ_NO", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BIL_FORM_attribute = addAttributeWithParams
        	(232, "BIL_FORM", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLI_PROFIL_attribute = addAttributeWithParams
        	(233, "DLI_PROFIL", "string", 
        	8, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REV_TYPE_attribute = addAttributeWithParams
        	(234, "REV_TYPE", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BEGDEM_PER_attribute = addAttributeWithParams
        	(235, "BEGDEM_PER", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PR_REF_MAT_attribute = addAttributeWithParams
        	(236, "PR_REF_MAT", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFOBJTYPE_attribute = addAttributeWithParams
        	(237, "REFOBJTYPE", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFOBJKEY_attribute = addAttributeWithParams
        	(238, "REFOBJKEY", "string", 
        	70, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(70)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REFLOGSYS_attribute = addAttributeWithParams
        	(239, "REFLOGSYS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ORDER_PROB_attribute = addAttributeWithParams
        	(240, "ORDER_PROB", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAX_PL_DLV_attribute = addAttributeWithParams
        	(241, "MAX_PL_DLV", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(1,0)", "", 1, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CFOP_CODE_attribute = addAttributeWithParams
        	(242, "CFOP_CODE", "string", 
        	5, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(5)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXLAWICMS_attribute = addAttributeWithParams
        	(243, "TAXLAWICMS", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXLAWIPI_attribute = addAttributeWithParams
        	(244, "TAXLAWIPI", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SD_TAXCODE_attribute = addAttributeWithParams
        	(245, "SD_TAXCODE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ASSORT_MOD_attribute = addAttributeWithParams
        	(246, "ASSORT_MOD", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COMP_QUANT_attribute = addAttributeWithParams
        	(247, "COMP_QUANT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(7,0)", "", 7, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TARGET_VAL_attribute = addAttributeWithParams
        	(248, "TARGET_VAL", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(15,0)", "", 15, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURRENCY_attribute = addAttributeWithParams
        	(249, "CURRENCY", "string", 
        	5, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(5)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURR_ISO_attribute = addAttributeWithParams
        	(250, "CURR_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PROFIT_CTR_attribute = addAttributeWithParams
        	(251, "PROFIT_CTR", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ORDERID_attribute = addAttributeWithParams
        	(252, "ORDERID", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData WBS_ELEM_attribute = addAttributeWithParams
        	(253, "WBS_ELEM", "string", 
        	24, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DEPREC_PER_attribute = addAttributeWithParams
        	(254, "DEPREC_PER", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(3,0)", "", 3, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_DOC_attribute = addAttributeWithParams
        	(255, "REF_DOC", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_DOC_IT_attribute = addAttributeWithParams
        	(256, "REF_DOC_IT", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_DOC_CA_attribute = addAttributeWithParams
        	(257, "REF_DOC_CA", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUST_MAT35_attribute = addAttributeWithParams
        	(258, "CUST_MAT35", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCH_RATE_FI_V_attribute = addAttributeWithParams
        	(259, "EXCH_RATE_FI_V", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCHG_RATE_V_attribute = addAttributeWithParams
        	(260, "EXCHG_RATE_V", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "decimal(5,0)", "", 5, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ITEMGUID_ATP_attribute = addAttributeWithParams
        	(261, "ITEMGUID_ATP", "string", 
        	22, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(22)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VAL_CONTR_attribute = addAttributeWithParams
        	(262, "VAL_CONTR", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VAL_CON_I_attribute = addAttributeWithParams
        	(263, "VAL_CON_I", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CONFIG_ID_attribute = addAttributeWithParams
        	(264, "CONFIG_ID", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(6)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData INST_ID_attribute = addAttributeWithParams
        	(265, "INST_ID", "string", 
        	8, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_EXT_attribute = addAttributeWithParams
        	(266, "MAT_EXT", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_GUID_attribute = addAttributeWithParams
        	(267, "MAT_GUID", "string", 
        	32, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(32)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_VERS_attribute = addAttributeWithParams
        	(268, "MAT_VERS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData P_MAT_EXT_attribute = addAttributeWithParams
        	(269, "P_MAT_EXT", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData P_MAT_GUID_attribute = addAttributeWithParams
        	(270, "P_MAT_GUID", "string", 
        	32, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(32)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData P_MAT_VERS_attribute = addAttributeWithParams
        	(271, "P_MAT_VERS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FUNC_AREA_attribute = addAttributeWithParams
        	(272, "FUNC_AREA", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ALTERN_BOM_attribute = addAttributeWithParams
        	(273, "ALTERN_BOM", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FKK_CONACCT_attribute = addAttributeWithParams
        	(274, "FKK_CONACCT", "string", 
        	12, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EAN_UPC_attribute = addAttributeWithParams
        	(275, "EAN_UPC", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRODCAT_attribute = addAttributeWithParams
        	(276, "PRODCAT", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHIP_TYPE_attribute = addAttributeWithParams
        	(277, "SHIP_TYPE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData S_PROC_IND_attribute = addAttributeWithParams
        	(278, "S_PROC_IND", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FUNC_AREA_LONG_attribute = addAttributeWithParams
        	(279, "FUNC_AREA_LONG", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_REL_attribute = addAttributeWithParams
        	(280, "BILL_REL", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VW_UEPOS_attribute = addAttributeWithParams
        	(281, "VW_UEPOS", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CAMPAIGN_attribute = addAttributeWithParams
        	(282, "CAMPAIGN", "binary", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varbinary(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLVSCHDUSE_attribute = addAttributeWithParams
        	(283, "DLVSCHDUSE", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CFOP_LONG_attribute = addAttributeWithParams
        	(284, "CFOP_LONG", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SELECTION_attribute = addAttributeWithParams
        	(285, "SELECTION", "string", 
        	32, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(32)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_ENTRD_attribute = addAttributeWithParams
        	(286, "MAT_ENTRD", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(18)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LOG_SYSTEM_OWN_attribute = addAttributeWithParams
        	(287, "LOG_SYSTEM_OWN", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ITM_TYPE_USAGE_attribute = addAttributeWithParams
        	(288, "ITM_TYPE_USAGE", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXLAWISS_attribute = addAttributeWithParams
        	(289, "TAXLAWISS", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_ENTRD_EXTERNAL_attribute = addAttributeWithParams
        	(290, "MAT_ENTRD_EXTERNAL", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_ENTRD_GUID_attribute = addAttributeWithParams
        	(291, "MAT_ENTRD_GUID", "string", 
        	32, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(32)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_ENTRD_VERSION_attribute = addAttributeWithParams
        	(292, "MAT_ENTRD_VERSION", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LOC_TAXCAT_attribute = addAttributeWithParams
        	(293, "LOC_TAXCAT", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LOC_ZEROVAT_attribute = addAttributeWithParams
        	(294, "LOC_ZEROVAT", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LOC_ACTCODE_attribute = addAttributeWithParams
        	(295, "LOC_ACTCODE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LOC_DISTTYPE_attribute = addAttributeWithParams
        	(296, "LOC_DISTTYPE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LOC_TXRELCLAS_attribute = addAttributeWithParams
        	(297, "LOC_TXRELCLAS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CALC_MOTIVE_attribute = addAttributeWithParams
        	(298, "CALC_MOTIVE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COMPREAS_attribute = addAttributeWithParams
        	(299, "COMPREAS", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FUND_attribute = addAttributeWithParams
        	(300, "FUND", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FUNDS_CTR_attribute = addAttributeWithParams
        	(301, "FUNDS_CTR", "string", 
        	16, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CMMT_ITEM_attribute = addAttributeWithParams
        	(302, "CMMT_ITEM", "string", 
        	24, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData GRANT_NBR_attribute = addAttributeWithParams
        	(303, "GRANT_NBR", "string", 
        	20, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(20)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BUDGET_PERIOD_attribute = addAttributeWithParams
        	(304, "BUDGET_PERIOD", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXLAWCOFINS_attribute = addAttributeWithParams
        	(305, "TAXLAWCOFINS", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData TAXLAWPIS_attribute = addAttributeWithParams
        	(306, "TAXLAWPIS", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(3)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("BAPI_SALESORDER_CREATEFROMDAT2_ORDER_ITEMS_IN");
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}