/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */  
package GBI_SalesApp.intrnl;

public class SalesOrderGetListMetaData
extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public SalesOrderGetListMetaData()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getMetaData());
        _init();
    }
    
    protected void _init()
    {
        setId(8);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData CUST_NUM_attribute = addAttributeWithParams
        	(388, "CUST_NUM", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"a\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SD_DOC_attribute = addAttributeWithParams
        	(389, "SD_DOC", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"b\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ITM_NUMBER_attribute = addAttributeWithParams
        	(390, "ITM_NUMBER", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"c\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATERIAL_attribute = addAttributeWithParams
        	(391, "MATERIAL", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"d\"", "varchar(72)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHORT_TEXT_attribute = addAttributeWithParams
        	(392, "SHORT_TEXT", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"e\"", "varchar(160)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_TYPE_attribute = addAttributeWithParams
        	(393, "DOC_TYPE", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"f\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQ_QTY_attribute = addAttributeWithParams
        	(394, "REQ_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"g\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_attribute = addAttributeWithParams
        	(395, "PURCH_NO", "string", 
        	20, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"h\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BATCH_attribute = addAttributeWithParams
        	(396, "BATCH", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"i\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BILL_BLOCK_attribute = addAttributeWithParams
        	(397, "BILL_BLOCK", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"j\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_BLOCK_attribute = addAttributeWithParams
        	(398, "DLV_BLOCK", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"l\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SOLD_TO_attribute = addAttributeWithParams
        	(399, "SOLD_TO", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"m\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NAME_attribute = addAttributeWithParams
        	(400, "NAME", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"n\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCHG_RATE_attribute = addAttributeWithParams
        	(401, "EXCHG_RATE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"o\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_QTY_attribute = addAttributeWithParams
        	(402, "DLV_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"p\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData BASE_UOM_attribute = addAttributeWithParams
        	(403, "BASE_UOM", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"q\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NET_PRICE_attribute = addAttributeWithParams
        	(404, "NET_PRICE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"r\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COND_P_UNT_attribute = addAttributeWithParams
        	(405, "COND_P_UNT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"s\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COND_UNIT_attribute = addAttributeWithParams
        	(406, "COND_UNIT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"t\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NET_VAL_HD_attribute = addAttributeWithParams
        	(407, "NET_VAL_HD", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"u\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NET_VALUE_attribute = addAttributeWithParams
        	(408, "NET_VALUE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"v\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DIVISION_attribute = addAttributeWithParams
        	(409, "DIVISION", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"w\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_STATUS_attribute = addAttributeWithParams
        	(410, "DOC_STATUS", "string", 
        	20, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"x\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_GRP_attribute = addAttributeWithParams
        	(411, "SALES_GRP", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"y\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_OFF_attribute = addAttributeWithParams
        	(412, "SALES_OFF", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"z\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_ORG_attribute = addAttributeWithParams
        	(413, "SALES_ORG", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"ba\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_UNIT_attribute = addAttributeWithParams
        	(414, "SALES_UNIT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bb\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHIP_POINT_attribute = addAttributeWithParams
        	(415, "SHIP_POINT", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bc\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DISTR_CHAN_attribute = addAttributeWithParams
        	(416, "DISTR_CHAN", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bd\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURRENCY_attribute = addAttributeWithParams
        	(417, "CURRENCY", "string", 
        	5, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"be\"", "varchar(20)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PLANT_attribute = addAttributeWithParams
        	(418, "PLANT", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bf\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData STORE_LOC_attribute = addAttributeWithParams
        	(419, "STORE_LOC", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bg\"", "varchar(16)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ORD_REASON_attribute = addAttributeWithParams
        	(420, "ORD_REASON", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bh\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REASON_REJ_attribute = addAttributeWithParams
        	(421, "REASON_REJ", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bi\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData B_UOM_ISO_attribute = addAttributeWithParams
        	(422, "B_UOM_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bj\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CD_UNT_ISO_attribute = addAttributeWithParams
        	(423, "CD_UNT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bl\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData S_UNIT_ISO_attribute = addAttributeWithParams
        	(424, "S_UNIT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bm\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURR_ISO_attribute = addAttributeWithParams
        	(425, "CURR_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bn\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_C_attribute = addAttributeWithParams
        	(426, "PURCH_NO_C", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bo\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData EXCHG_RATE_V_attribute = addAttributeWithParams
        	(427, "EXCHG_RATE_V", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bp\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_EXT_attribute = addAttributeWithParams
        	(428, "MAT_EXT", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bq\"", "varchar(160)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_GUID_attribute = addAttributeWithParams
        	(429, "MAT_GUID", "string", 
        	32, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"br\"", "varchar(128)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MAT_VERS_attribute = addAttributeWithParams
        	(430, "MAT_VERS", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bs\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData STATUS_DOC_attribute = addAttributeWithParams
        	(431, "STATUS_DOC", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bt\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_DATE_attribute = addAttributeWithParams
        	(432, "DOC_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bu\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQ_DATE_attribute = addAttributeWithParams
        	(433, "REQ_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bv\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VALID_FROM_attribute = addAttributeWithParams
        	(434, "VALID_FROM", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bw\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VALID_TO_attribute = addAttributeWithParams
        	(435, "VALID_TO", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bx\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData GI_DATE_attribute = addAttributeWithParams
        	(436, "GI_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"by\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CREATION_DATE_attribute = addAttributeWithParams
        	(437, "CREATION_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bz\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CREATION_TIME_attribute = addAttributeWithParams
        	(438, "CREATION_TIME", "time?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"ca\"", "time", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData pending_attribute = addAttributeWithParams
        	(20001, "pending", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"pending\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData pendingChange_attribute = addAttributeWithParams
        	(20002, "pendingChange", "char", 
        	1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_pc\"", "char(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData replayPending_attribute = addAttributeWithParams
        	(20005, "replayPending", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_rp\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData replayFailure_attribute = addAttributeWithParams
        	(20006, "replayFailure", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_rf\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData surrogateKey_attribute = addAttributeWithParams
        	(439, "surrogateKey", "long", 
        	-1, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"cb\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.GLOBAL,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData replayCounter_attribute = addAttributeWithParams
        	(20004, "replayCounter", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_rc\"", "bigint", "_rc", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData disableSubmit_attribute = addAttributeWithParams
        	(20003, "disableSubmit", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_ds\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("SalesOrderGetList");
        setTable("\"gbi_salesapp_1_0_salesordergetlist\"");
        setSynchronizationGroup("SynchronizationGroup2");
        this.getKeyAttributes().add((surrogateKey_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}