/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */  
package GBI_SalesApp.intrnl;

public class SalesOrderGetStatusMetaData
extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public SalesOrderGetStatusMetaData()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getMetaData());
        _init();
    }
    
    protected void _init()
    {
        setId(9);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData DOC_NUMBER_attribute = addAttributeWithParams
        	(440, "DOC_NUMBER", "string", 
        	20, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"a\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_attribute = addAttributeWithParams
        	(441, "PURCH_NO", "string", 
        	20, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"b\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PRC_STAT_H_attribute = addAttributeWithParams
        	(442, "PRC_STAT_H", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"c\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_STAT_H_attribute = addAttributeWithParams
        	(443, "DLV_STAT_H", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"d\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_BLOCK_attribute = addAttributeWithParams
        	(444, "DLV_BLOCK", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"e\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ITM_NUMBER_attribute = addAttributeWithParams
        	(445, "ITM_NUMBER", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"f\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATERIAL_attribute = addAttributeWithParams
        	(446, "MATERIAL", "string", 
        	18, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"g\"", "varchar(72)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SHORT_TEXT_attribute = addAttributeWithParams
        	(447, "SHORT_TEXT", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"h\"", "varchar(160)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQ_QTY_attribute = addAttributeWithParams
        	(448, "REQ_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"i\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CUM_CF_QTY_attribute = addAttributeWithParams
        	(449, "CUM_CF_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"j\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SALES_UNIT_attribute = addAttributeWithParams
        	(450, "SALES_UNIT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"l\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NET_VALUE_attribute = addAttributeWithParams
        	(451, "NET_VALUE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"m\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURRENCY_attribute = addAttributeWithParams
        	(452, "CURRENCY", "string", 
        	5, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"n\"", "varchar(20)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData NET_PRICE_attribute = addAttributeWithParams
        	(453, "NET_PRICE", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"o\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COND_P_UNT_attribute = addAttributeWithParams
        	(454, "COND_P_UNT", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"p\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData COND_UNIT_attribute = addAttributeWithParams
        	(455, "COND_UNIT", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"q\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_STAT_I_attribute = addAttributeWithParams
        	(456, "DLV_STAT_I", "string", 
        	1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"r\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DELIV_NUMB_attribute = addAttributeWithParams
        	(457, "DELIV_NUMB", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"s\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DELIV_ITEM_attribute = addAttributeWithParams
        	(458, "DELIV_ITEM", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"t\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_QTY_attribute = addAttributeWithParams
        	(459, "DLV_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"u\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REF_QTY_attribute = addAttributeWithParams
        	(460, "REF_QTY", "decimal", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"v\"", "decimal(28,8)", "", 28, 8, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData S_UNIT_ISO_attribute = addAttributeWithParams
        	(461, "S_UNIT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"w\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CD_UNT_ISO_attribute = addAttributeWithParams
        	(462, "CD_UNT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"x\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CURR_ISO_attribute = addAttributeWithParams
        	(463, "CURR_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"y\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATERIAL_EXTERNAL_attribute = addAttributeWithParams
        	(464, "MATERIAL_EXTERNAL", "string", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"z\"", "varchar(160)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATERIAL_GUID_attribute = addAttributeWithParams
        	(465, "MATERIAL_GUID", "string", 
        	32, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"ba\"", "varchar(128)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData MATERIAL_VERSION_attribute = addAttributeWithParams
        	(466, "MATERIAL_VERSION", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bb\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PO_ITM_NO_attribute = addAttributeWithParams
        	(467, "PO_ITM_NO", "string", 
        	6, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bc\"", "varchar(24)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData S_UNIT_DLV_attribute = addAttributeWithParams
        	(468, "S_UNIT_DLV", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bd\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DLV_UNIT_ISO_attribute = addAttributeWithParams
        	(469, "DLV_UNIT_ISO", "string", 
        	3, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"be\"", "varchar(12)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REA_FOR_RE_attribute = addAttributeWithParams
        	(470, "REA_FOR_RE", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bf\"", "varchar(8)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PURCH_NO_C_attribute = addAttributeWithParams
        	(471, "PURCH_NO_C", "string", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bg\"", "varchar(140)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DOC_DATE_attribute = addAttributeWithParams
        	(472, "DOC_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bh\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQ_DATE_H_attribute = addAttributeWithParams
        	(473, "REQ_DATE_H", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bi\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData REQ_DATE_attribute = addAttributeWithParams
        	(474, "REQ_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bj\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DELIV_DATE_attribute = addAttributeWithParams
        	(475, "DELIV_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bl\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CREATION_DATE_attribute = addAttributeWithParams
        	(476, "CREATION_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bm\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CREATION_TIME_attribute = addAttributeWithParams
        	(477, "CREATION_TIME", "time?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"bn\"", "time", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData pending_attribute = addAttributeWithParams
        	(20001, "pending", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"pending\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData pendingChange_attribute = addAttributeWithParams
        	(20002, "pendingChange", "char", 
        	1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_pc\"", "char(1)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData replayPending_attribute = addAttributeWithParams
        	(20005, "replayPending", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_rp\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData replayFailure_attribute = addAttributeWithParams
        	(20006, "replayFailure", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_rf\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData surrogateKey_attribute = addAttributeWithParams
        	(478, "surrogateKey", "long", 
        	-1, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"bo\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.GLOBAL,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData replayCounter_attribute = addAttributeWithParams
        	(20004, "replayCounter", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_rc\"", "bigint", "_rc", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData disableSubmit_attribute = addAttributeWithParams
        	(20003, "disableSubmit", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"_ds\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("SalesOrderGetStatus");
        setTable("\"gbi_salesapp_1_0_salesordergetstatus\"");
        setSynchronizationGroup("default");
        this.getKeyAttributes().add((surrogateKey_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}