/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp.intrnl;

public  class SISSubscriptionKey extends com.sybase.sup.client.persistence.SISSubscriptionKey implements com.sybase.reflection.ClassWithMetaData
{
    private static GBI_SalesApp.intrnl.SISSubscriptionKeyMetaData META_DATA = new GBI_SalesApp.intrnl.SISSubscriptionKeyMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("SISSubscriptionKey", GBI_SalesApp.intrnl.SISSubscriptionKey.class, META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
}