/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp.intrnl;

public  class SISSubscription extends com.sybase.sup.client.persistence.SISSubscription implements com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static GBI_SalesApp.intrnl.SISSubscriptionMetaData META_DATA = new GBI_SalesApp.intrnl.SISSubscriptionMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("SISSubscription", GBI_SalesApp.intrnl.SISSubscription.class, "GBI_SalesApp.SISSubscription", META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
}