/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_IN extends com.sybase.persistence.AbstractStructure implements com.sybase.reflection.ClassWithMetaData
{
    private static GBI_SalesApp.intrnl.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_INMetaData META_DATA = new GBI_SalesApp.intrnl.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_INMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_IN", GBI_SalesApp.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_IN.class, META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
    
    /**
     * Creates an instance of GBI_SalesApp.BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_IN  
     */
    public BAPI_SALESORDER_CREATEFROMDAT2_ORDER_HEADER_IN()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    
    private java.lang.String __REFOBJTYPE ;  
    
    private java.lang.String __REFOBJKEY ;  
    
    private java.lang.String __REFDOCTYPE ;  
    
    private java.lang.String __DOC_TYPE ;  
    
    private java.lang.String __COLLECT_NO ;  
    
    private java.lang.String __SALES_ORG ;  
    
    private java.lang.String __DISTR_CHAN ;  
    
    private java.lang.String __DIVISION ;  
    
    private java.lang.String __SALES_GRP ;  
    
    private java.lang.String __SALES_OFF ;  
    
    private java.sql.Date __REQ_DATE_H ;  
    
    private java.lang.String __DATE_TYPE ;  
    
    private java.sql.Date __PURCH_DATE ;  
    
    private java.lang.String __PO_METHOD ;  
    
    private java.lang.String __PO_SUPPLEM ;  
    
    private java.lang.String __REF_1 ;  
    
    private java.lang.String __NAME ;  
    
    private java.lang.String __TELEPHONE ;  
    
    private java.lang.String __PRICE_GRP ;  
    
    private java.lang.String __CUST_GROUP ;  
    
    private java.lang.String __SALES_DIST ;  
    
    private java.lang.String __PRICE_LIST ;  
    
    private java.lang.String __INCOTERMS1 ;  
    
    private java.lang.String __INCOTERMS2 ;  
    
    private java.lang.String __PMNTTRMS ;  
    
    private java.lang.String __DLV_BLOCK ;  
    
    private java.lang.String __BILL_BLOCK ;  
    
    private java.lang.String __ORD_REASON ;  
    
    private java.lang.String __COMPL_DLV ;  
    
    private java.sql.Date __PRICE_DATE ;  
    
    private java.sql.Date __QT_VALID_F ;  
    
    private java.sql.Date __QT_VALID_T ;  
    
    private java.sql.Date __CT_VALID_F ;  
    
    private java.sql.Date __CT_VALID_T ;  
    
    private java.lang.String __CUST_GRP1 ;  
    
    private java.lang.String __CUST_GRP2 ;  
    
    private java.lang.String __CUST_GRP3 ;  
    
    private java.lang.String __CUST_GRP4 ;  
    
    private java.lang.String __CUST_GRP5 ;  
    
    private java.lang.String __PURCH_NO_C ;  
    
    private java.lang.String __PURCH_NO_S ;  
    
    private java.sql.Date __PO_DAT_S ;  
    
    private java.lang.String __PO_METH_S ;  
    
    private java.lang.String __REF_1_S ;  
    
    private java.lang.String __SD_DOC_CAT ;  
    
    private java.sql.Date __DOC_DATE ;  
    
    private java.sql.Date __WAR_DATE ;  
    
    private java.lang.String __SHIP_COND ;  
    
    private java.lang.String __PP_SEARCH ;  
    
    private java.math.BigDecimal __DUN_COUNT ;  
    
    private java.sql.Date __DUN_DATE ;  
    
    private java.lang.String __DLVSCHDUSE ;  
    
    private java.lang.String __PLDLVSTYP ;  
    
    private java.lang.String __REF_DOC ;  
    
    private java.lang.String __COMP_CDE_B ;  
    
    private java.lang.String __ALTTAX_CLS ;  
    
    private java.lang.String __TAX_CLASS2 ;  
    
    private java.lang.String __TAX_CLASS3 ;  
    
    private java.lang.String __TAX_CLASS4 ;  
    
    private java.lang.String __TAX_CLASS5 ;  
    
    private java.lang.String __TAX_CLASS6 ;  
    
    private java.lang.String __TAX_CLASS7 ;  
    
    private java.lang.String __TAX_CLASS8 ;  
    
    private java.lang.String __TAX_CLASS9 ;  
    
    private java.lang.String __REF_DOC_L ;  
    
    private java.lang.String __ASS_NUMBER ;  
    
    private java.lang.String __REFDOC_CAT ;  
    
    private java.lang.String __ORDCOMB_IN ;  
    
    private java.lang.String __BILL_SCHED ;  
    
    private java.lang.String __INVO_SCHED ;  
    
    private java.lang.String __MN_INVOICE ;  
    
    private java.math.BigDecimal __EXRATE_FI ;  
    
    private java.lang.String __ADD_VAL_DY ;  
    
    private java.sql.Date __FIX_VAL_DY ;  
    
    private java.lang.String __PYMT_METH ;  
    
    private java.lang.String __ACCNT_ASGN ;  
    
    private java.math.BigDecimal __EXCHG_RATE ;  
    
    private java.sql.Date __BILL_DATE ;  
    
    private java.sql.Date __SERV_DATE ;  
    
    private java.lang.String __DUNN_KEY ;  
    
    private java.lang.String __DUNN_BLOCK ;  
    
    private java.lang.String __PMTGAR_PRO ;  
    
    private java.lang.String __DEPARTM_NO ;  
    
    private java.lang.String __REC_POINT ;  
    
    private java.lang.String __DOC_NUM_FI ;  
    
    private java.lang.String __CSTCNDGRP1 ;  
    
    private java.lang.String __CSTCNDGRP2 ;  
    
    private java.lang.String __CSTCNDGRP3 ;  
    
    private java.lang.String __CSTCNDGRP4 ;  
    
    private java.lang.String __CSTCNDGRP5 ;  
    
    private java.lang.String __DLV_TIME ;  
    
    private java.lang.String __CURRENCY ;  
    
    private java.lang.String __CURR_ISO ;  
    
    private java.lang.String __CREATED_BY ;  
    
    private java.lang.String __TAXDEP_CTY ;  
    
    private java.lang.String __TAXDST_CTY ;  
    
    private java.lang.String __EUTRI_DEAL ;  
    
    private java.lang.String __MAST_CONTR ;  
    
    private java.lang.String __REF_PROC ;  
    
    private java.lang.String __CHKPRTAUTH ;  
    
    private java.sql.Date __CMLQTY_DAT ;  
    
    private java.lang.String __VERSION ;  
    
    private java.lang.String __NOTIF_NO ;  
    
    private java.lang.String __WBS_ELEM ;  
    
    private java.math.BigDecimal __EXCH_RATE_FI_V ;  
    
    private java.math.BigDecimal __EXCHG_RATE_V ;  
    
    private java.lang.String __FKK_CONACCT ;  
    
    private byte[] __CAMPAIGN ;  
    
    private java.lang.String __DOC_CLASS ;  
    
    private java.lang.String __H_CURR ;  
    
    private java.lang.String __H_CURR_ISO ;  
    
    private java.lang.String __SHIP_TYPE ;  
    
    private java.lang.String __S_PROC_IND ;  
    
    private java.lang.String __REF_DOC_L_LONG ;  
    
    private java.sql.Time __LINE_TIME ;  
    
    private java.lang.String __CALC_MOTIVE ;  
    
    public byte[] getAttributeBinary(int id)
    {
        switch(id)
        {
        case 107:
            return getCAMPAIGN();
        default:
            return super.getAttributeBinary(id);
        }
    }
    
    public void setAttributeBinary(int id, byte[] v)
    {
        switch(id)
        {
        case 107:
            setCAMPAIGN((byte[])v);
            break;
        default:
            super.setAttributeBinary(id, v);
            break;
        }
    }
    public java.math.BigDecimal getAttributeDecimal(int id)
    {
        switch(id)
        {
        case 49:
            return getDUN_COUNT();
        case 71:
            return getEXRATE_FI();
        case 76:
            return getEXCHG_RATE();
        case 104:
            return getEXCH_RATE_FI_V();
        case 105:
            return getEXCHG_RATE_V();
        default:
            return super.getAttributeDecimal(id);
        }
    }
    
    public void setAttributeDecimal(int id, java.math.BigDecimal v)
    {
        switch(id)
        {
        case 49:
            setDUN_COUNT((java.math.BigDecimal)v);
            break;
        case 71:
            setEXRATE_FI((java.math.BigDecimal)v);
            break;
        case 76:
            setEXCHG_RATE((java.math.BigDecimal)v);
            break;
        case 104:
            setEXCH_RATE_FI_V((java.math.BigDecimal)v);
            break;
        case 105:
            setEXCHG_RATE_V((java.math.BigDecimal)v);
            break;
        default:
            super.setAttributeDecimal(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 0:
            return getREFOBJTYPE();
        case 1:
            return getREFOBJKEY();
        case 2:
            return getREFDOCTYPE();
        case 3:
            return getDOC_TYPE();
        case 4:
            return getCOLLECT_NO();
        case 5:
            return getSALES_ORG();
        case 6:
            return getDISTR_CHAN();
        case 7:
            return getDIVISION();
        case 8:
            return getSALES_GRP();
        case 9:
            return getSALES_OFF();
        case 11:
            return getDATE_TYPE();
        case 13:
            return getPO_METHOD();
        case 14:
            return getPO_SUPPLEM();
        case 15:
            return getREF_1();
        case 16:
            return getNAME();
        case 17:
            return getTELEPHONE();
        case 18:
            return getPRICE_GRP();
        case 19:
            return getCUST_GROUP();
        case 20:
            return getSALES_DIST();
        case 21:
            return getPRICE_LIST();
        case 22:
            return getINCOTERMS1();
        case 23:
            return getINCOTERMS2();
        case 24:
            return getPMNTTRMS();
        case 25:
            return getDLV_BLOCK();
        case 26:
            return getBILL_BLOCK();
        case 27:
            return getORD_REASON();
        case 28:
            return getCOMPL_DLV();
        case 34:
            return getCUST_GRP1();
        case 35:
            return getCUST_GRP2();
        case 36:
            return getCUST_GRP3();
        case 37:
            return getCUST_GRP4();
        case 38:
            return getCUST_GRP5();
        case 39:
            return getPURCH_NO_C();
        case 40:
            return getPURCH_NO_S();
        case 42:
            return getPO_METH_S();
        case 43:
            return getREF_1_S();
        case 44:
            return getSD_DOC_CAT();
        case 47:
            return getSHIP_COND();
        case 48:
            return getPP_SEARCH();
        case 51:
            return getDLVSCHDUSE();
        case 52:
            return getPLDLVSTYP();
        case 53:
            return getREF_DOC();
        case 54:
            return getCOMP_CDE_B();
        case 55:
            return getALTTAX_CLS();
        case 56:
            return getTAX_CLASS2();
        case 57:
            return getTAX_CLASS3();
        case 58:
            return getTAX_CLASS4();
        case 59:
            return getTAX_CLASS5();
        case 60:
            return getTAX_CLASS6();
        case 61:
            return getTAX_CLASS7();
        case 62:
            return getTAX_CLASS8();
        case 63:
            return getTAX_CLASS9();
        case 64:
            return getREF_DOC_L();
        case 65:
            return getASS_NUMBER();
        case 66:
            return getREFDOC_CAT();
        case 67:
            return getORDCOMB_IN();
        case 68:
            return getBILL_SCHED();
        case 69:
            return getINVO_SCHED();
        case 70:
            return getMN_INVOICE();
        case 72:
            return getADD_VAL_DY();
        case 74:
            return getPYMT_METH();
        case 75:
            return getACCNT_ASGN();
        case 79:
            return getDUNN_KEY();
        case 80:
            return getDUNN_BLOCK();
        case 81:
            return getPMTGAR_PRO();
        case 82:
            return getDEPARTM_NO();
        case 83:
            return getREC_POINT();
        case 84:
            return getDOC_NUM_FI();
        case 85:
            return getCSTCNDGRP1();
        case 86:
            return getCSTCNDGRP2();
        case 87:
            return getCSTCNDGRP3();
        case 88:
            return getCSTCNDGRP4();
        case 89:
            return getCSTCNDGRP5();
        case 90:
            return getDLV_TIME();
        case 91:
            return getCURRENCY();
        case 92:
            return getCURR_ISO();
        case 93:
            return getCREATED_BY();
        case 94:
            return getTAXDEP_CTY();
        case 95:
            return getTAXDST_CTY();
        case 96:
            return getEUTRI_DEAL();
        case 97:
            return getMAST_CONTR();
        case 98:
            return getREF_PROC();
        case 99:
            return getCHKPRTAUTH();
        case 101:
            return getVERSION();
        case 102:
            return getNOTIF_NO();
        case 103:
            return getWBS_ELEM();
        case 106:
            return getFKK_CONACCT();
        case 108:
            return getDOC_CLASS();
        case 109:
            return getH_CURR();
        case 110:
            return getH_CURR_ISO();
        case 111:
            return getSHIP_TYPE();
        case 112:
            return getS_PROC_IND();
        case 113:
            return getREF_DOC_L_LONG();
        case 115:
            return getCALC_MOTIVE();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 0:
            setREFOBJTYPE((java.lang.String)v);
            break;
        case 1:
            setREFOBJKEY((java.lang.String)v);
            break;
        case 2:
            setREFDOCTYPE((java.lang.String)v);
            break;
        case 3:
            setDOC_TYPE((java.lang.String)v);
            break;
        case 4:
            setCOLLECT_NO((java.lang.String)v);
            break;
        case 5:
            setSALES_ORG((java.lang.String)v);
            break;
        case 6:
            setDISTR_CHAN((java.lang.String)v);
            break;
        case 7:
            setDIVISION((java.lang.String)v);
            break;
        case 8:
            setSALES_GRP((java.lang.String)v);
            break;
        case 9:
            setSALES_OFF((java.lang.String)v);
            break;
        case 11:
            setDATE_TYPE((java.lang.String)v);
            break;
        case 13:
            setPO_METHOD((java.lang.String)v);
            break;
        case 14:
            setPO_SUPPLEM((java.lang.String)v);
            break;
        case 15:
            setREF_1((java.lang.String)v);
            break;
        case 16:
            setNAME((java.lang.String)v);
            break;
        case 17:
            setTELEPHONE((java.lang.String)v);
            break;
        case 18:
            setPRICE_GRP((java.lang.String)v);
            break;
        case 19:
            setCUST_GROUP((java.lang.String)v);
            break;
        case 20:
            setSALES_DIST((java.lang.String)v);
            break;
        case 21:
            setPRICE_LIST((java.lang.String)v);
            break;
        case 22:
            setINCOTERMS1((java.lang.String)v);
            break;
        case 23:
            setINCOTERMS2((java.lang.String)v);
            break;
        case 24:
            setPMNTTRMS((java.lang.String)v);
            break;
        case 25:
            setDLV_BLOCK((java.lang.String)v);
            break;
        case 26:
            setBILL_BLOCK((java.lang.String)v);
            break;
        case 27:
            setORD_REASON((java.lang.String)v);
            break;
        case 28:
            setCOMPL_DLV((java.lang.String)v);
            break;
        case 34:
            setCUST_GRP1((java.lang.String)v);
            break;
        case 35:
            setCUST_GRP2((java.lang.String)v);
            break;
        case 36:
            setCUST_GRP3((java.lang.String)v);
            break;
        case 37:
            setCUST_GRP4((java.lang.String)v);
            break;
        case 38:
            setCUST_GRP5((java.lang.String)v);
            break;
        case 39:
            setPURCH_NO_C((java.lang.String)v);
            break;
        case 40:
            setPURCH_NO_S((java.lang.String)v);
            break;
        case 42:
            setPO_METH_S((java.lang.String)v);
            break;
        case 43:
            setREF_1_S((java.lang.String)v);
            break;
        case 44:
            setSD_DOC_CAT((java.lang.String)v);
            break;
        case 47:
            setSHIP_COND((java.lang.String)v);
            break;
        case 48:
            setPP_SEARCH((java.lang.String)v);
            break;
        case 51:
            setDLVSCHDUSE((java.lang.String)v);
            break;
        case 52:
            setPLDLVSTYP((java.lang.String)v);
            break;
        case 53:
            setREF_DOC((java.lang.String)v);
            break;
        case 54:
            setCOMP_CDE_B((java.lang.String)v);
            break;
        case 55:
            setALTTAX_CLS((java.lang.String)v);
            break;
        case 56:
            setTAX_CLASS2((java.lang.String)v);
            break;
        case 57:
            setTAX_CLASS3((java.lang.String)v);
            break;
        case 58:
            setTAX_CLASS4((java.lang.String)v);
            break;
        case 59:
            setTAX_CLASS5((java.lang.String)v);
            break;
        case 60:
            setTAX_CLASS6((java.lang.String)v);
            break;
        case 61:
            setTAX_CLASS7((java.lang.String)v);
            break;
        case 62:
            setTAX_CLASS8((java.lang.String)v);
            break;
        case 63:
            setTAX_CLASS9((java.lang.String)v);
            break;
        case 64:
            setREF_DOC_L((java.lang.String)v);
            break;
        case 65:
            setASS_NUMBER((java.lang.String)v);
            break;
        case 66:
            setREFDOC_CAT((java.lang.String)v);
            break;
        case 67:
            setORDCOMB_IN((java.lang.String)v);
            break;
        case 68:
            setBILL_SCHED((java.lang.String)v);
            break;
        case 69:
            setINVO_SCHED((java.lang.String)v);
            break;
        case 70:
            setMN_INVOICE((java.lang.String)v);
            break;
        case 72:
            setADD_VAL_DY((java.lang.String)v);
            break;
        case 74:
            setPYMT_METH((java.lang.String)v);
            break;
        case 75:
            setACCNT_ASGN((java.lang.String)v);
            break;
        case 79:
            setDUNN_KEY((java.lang.String)v);
            break;
        case 80:
            setDUNN_BLOCK((java.lang.String)v);
            break;
        case 81:
            setPMTGAR_PRO((java.lang.String)v);
            break;
        case 82:
            setDEPARTM_NO((java.lang.String)v);
            break;
        case 83:
            setREC_POINT((java.lang.String)v);
            break;
        case 84:
            setDOC_NUM_FI((java.lang.String)v);
            break;
        case 85:
            setCSTCNDGRP1((java.lang.String)v);
            break;
        case 86:
            setCSTCNDGRP2((java.lang.String)v);
            break;
        case 87:
            setCSTCNDGRP3((java.lang.String)v);
            break;
        case 88:
            setCSTCNDGRP4((java.lang.String)v);
            break;
        case 89:
            setCSTCNDGRP5((java.lang.String)v);
            break;
        case 90:
            setDLV_TIME((java.lang.String)v);
            break;
        case 91:
            setCURRENCY((java.lang.String)v);
            break;
        case 92:
            setCURR_ISO((java.lang.String)v);
            break;
        case 93:
            setCREATED_BY((java.lang.String)v);
            break;
        case 94:
            setTAXDEP_CTY((java.lang.String)v);
            break;
        case 95:
            setTAXDST_CTY((java.lang.String)v);
            break;
        case 96:
            setEUTRI_DEAL((java.lang.String)v);
            break;
        case 97:
            setMAST_CONTR((java.lang.String)v);
            break;
        case 98:
            setREF_PROC((java.lang.String)v);
            break;
        case 99:
            setCHKPRTAUTH((java.lang.String)v);
            break;
        case 101:
            setVERSION((java.lang.String)v);
            break;
        case 102:
            setNOTIF_NO((java.lang.String)v);
            break;
        case 103:
            setWBS_ELEM((java.lang.String)v);
            break;
        case 106:
            setFKK_CONACCT((java.lang.String)v);
            break;
        case 108:
            setDOC_CLASS((java.lang.String)v);
            break;
        case 109:
            setH_CURR((java.lang.String)v);
            break;
        case 110:
            setH_CURR_ISO((java.lang.String)v);
            break;
        case 111:
            setSHIP_TYPE((java.lang.String)v);
            break;
        case 112:
            setS_PROC_IND((java.lang.String)v);
            break;
        case 113:
            setREF_DOC_L_LONG((java.lang.String)v);
            break;
        case 115:
            setCALC_MOTIVE((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.sql.Time getAttributeNullableTime(int id)
    {
        switch(id)
        {
        case 114:
            return getLINE_TIME();
        default:
            return super.getAttributeNullableTime(id);
        }
    }
    
    public void setAttributeNullableTime(int id, java.sql.Time v)
    {
        switch(id)
        {
        case 114:
            setLINE_TIME((java.sql.Time)v);
            break;
        default:
            super.setAttributeNullableTime(id, v);
            break;
        }
    }
    public java.sql.Date getAttributeNullableDate(int id)
    {
        switch(id)
        {
        case 10:
            return getREQ_DATE_H();
        case 12:
            return getPURCH_DATE();
        case 29:
            return getPRICE_DATE();
        case 30:
            return getQT_VALID_F();
        case 31:
            return getQT_VALID_T();
        case 32:
            return getCT_VALID_F();
        case 33:
            return getCT_VALID_T();
        case 41:
            return getPO_DAT_S();
        case 45:
            return getDOC_DATE();
        case 46:
            return getWAR_DATE();
        case 50:
            return getDUN_DATE();
        case 73:
            return getFIX_VAL_DY();
        case 77:
            return getBILL_DATE();
        case 78:
            return getSERV_DATE();
        case 100:
            return getCMLQTY_DAT();
        default:
            return super.getAttributeNullableDate(id);
        }
    }
    
    public void setAttributeNullableDate(int id, java.sql.Date v)
    {
        switch(id)
        {
        case 10:
            setREQ_DATE_H((java.sql.Date)v);
            break;
        case 12:
            setPURCH_DATE((java.sql.Date)v);
            break;
        case 29:
            setPRICE_DATE((java.sql.Date)v);
            break;
        case 30:
            setQT_VALID_F((java.sql.Date)v);
            break;
        case 31:
            setQT_VALID_T((java.sql.Date)v);
            break;
        case 32:
            setCT_VALID_F((java.sql.Date)v);
            break;
        case 33:
            setCT_VALID_T((java.sql.Date)v);
            break;
        case 41:
            setPO_DAT_S((java.sql.Date)v);
            break;
        case 45:
            setDOC_DATE((java.sql.Date)v);
            break;
        case 46:
            setWAR_DATE((java.sql.Date)v);
            break;
        case 50:
            setDUN_DATE((java.sql.Date)v);
            break;
        case 73:
            setFIX_VAL_DY((java.sql.Date)v);
            break;
        case 77:
            setBILL_DATE((java.sql.Date)v);
            break;
        case 78:
            setSERV_DATE((java.sql.Date)v);
            break;
        case 100:
            setCMLQTY_DAT((java.sql.Date)v);
            break;
        default:
            super.setAttributeNullableDate(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of REFOBJTYPE  
     */
    public java.lang.String getREFOBJTYPE()
    {
        
        return __REFOBJTYPE;
    }
    
    /**
     * Set the value of REFOBJTYPE  
     */
    public void setREFOBJTYPE(java.lang.String value)
    {
        __REFOBJTYPE = value;
    }
    
    /**
     * get the value of REFOBJKEY  
     */
    public java.lang.String getREFOBJKEY()
    {
        
        return __REFOBJKEY;
    }
    
    /**
     * Set the value of REFOBJKEY  
     */
    public void setREFOBJKEY(java.lang.String value)
    {
        __REFOBJKEY = value;
    }
    
    /**
     * get the value of REFDOCTYPE  
     */
    public java.lang.String getREFDOCTYPE()
    {
        
        return __REFDOCTYPE;
    }
    
    /**
     * Set the value of REFDOCTYPE  
     */
    public void setREFDOCTYPE(java.lang.String value)
    {
        __REFDOCTYPE = value;
    }
    
    /**
     * get the value of DOC_TYPE  
     */
    public java.lang.String getDOC_TYPE()
    {
        
        return __DOC_TYPE;
    }
    
    /**
     * Set the value of DOC_TYPE  
     */
    public void setDOC_TYPE(java.lang.String value)
    {
        __DOC_TYPE = value;
    }
    
    /**
     * get the value of COLLECT_NO  
     */
    public java.lang.String getCOLLECT_NO()
    {
        
        return __COLLECT_NO;
    }
    
    /**
     * Set the value of COLLECT_NO  
     */
    public void setCOLLECT_NO(java.lang.String value)
    {
        __COLLECT_NO = value;
    }
    
    /**
     * get the value of SALES_ORG  
     */
    public java.lang.String getSALES_ORG()
    {
        
        return __SALES_ORG;
    }
    
    /**
     * Set the value of SALES_ORG  
     */
    public void setSALES_ORG(java.lang.String value)
    {
        __SALES_ORG = value;
    }
    
    /**
     * get the value of DISTR_CHAN  
     */
    public java.lang.String getDISTR_CHAN()
    {
        
        return __DISTR_CHAN;
    }
    
    /**
     * Set the value of DISTR_CHAN  
     */
    public void setDISTR_CHAN(java.lang.String value)
    {
        __DISTR_CHAN = value;
    }
    
    /**
     * get the value of DIVISION  
     */
    public java.lang.String getDIVISION()
    {
        
        return __DIVISION;
    }
    
    /**
     * Set the value of DIVISION  
     */
    public void setDIVISION(java.lang.String value)
    {
        __DIVISION = value;
    }
    
    /**
     * get the value of SALES_GRP  
     */
    public java.lang.String getSALES_GRP()
    {
        
        return __SALES_GRP;
    }
    
    /**
     * Set the value of SALES_GRP  
     */
    public void setSALES_GRP(java.lang.String value)
    {
        __SALES_GRP = value;
    }
    
    /**
     * get the value of SALES_OFF  
     */
    public java.lang.String getSALES_OFF()
    {
        
        return __SALES_OFF;
    }
    
    /**
     * Set the value of SALES_OFF  
     */
    public void setSALES_OFF(java.lang.String value)
    {
        __SALES_OFF = value;
    }
    
    /**
     * get the value of REQ_DATE_H  
     */
    public java.sql.Date getREQ_DATE_H()
    {
        
        return __REQ_DATE_H;
    }
    
    /**
     * Set the value of REQ_DATE_H  
     */
    public void setREQ_DATE_H(java.sql.Date value)
    {
        __REQ_DATE_H = value;
    }
    
    /**
     * get the value of DATE_TYPE  
     */
    public java.lang.String getDATE_TYPE()
    {
        
        return __DATE_TYPE;
    }
    
    /**
     * Set the value of DATE_TYPE  
     */
    public void setDATE_TYPE(java.lang.String value)
    {
        __DATE_TYPE = value;
    }
    
    /**
     * get the value of PURCH_DATE  
     */
    public java.sql.Date getPURCH_DATE()
    {
        
        return __PURCH_DATE;
    }
    
    /**
     * Set the value of PURCH_DATE  
     */
    public void setPURCH_DATE(java.sql.Date value)
    {
        __PURCH_DATE = value;
    }
    
    /**
     * get the value of PO_METHOD  
     */
    public java.lang.String getPO_METHOD()
    {
        
        return __PO_METHOD;
    }
    
    /**
     * Set the value of PO_METHOD  
     */
    public void setPO_METHOD(java.lang.String value)
    {
        __PO_METHOD = value;
    }
    
    /**
     * get the value of PO_SUPPLEM  
     */
    public java.lang.String getPO_SUPPLEM()
    {
        
        return __PO_SUPPLEM;
    }
    
    /**
     * Set the value of PO_SUPPLEM  
     */
    public void setPO_SUPPLEM(java.lang.String value)
    {
        __PO_SUPPLEM = value;
    }
    
    /**
     * get the value of REF_1  
     */
    public java.lang.String getREF_1()
    {
        
        return __REF_1;
    }
    
    /**
     * Set the value of REF_1  
     */
    public void setREF_1(java.lang.String value)
    {
        __REF_1 = value;
    }
    
    /**
     * get the value of NAME  
     */
    public java.lang.String getNAME()
    {
        
        return __NAME;
    }
    
    /**
     * Set the value of NAME  
     */
    public void setNAME(java.lang.String value)
    {
        __NAME = value;
    }
    
    /**
     * get the value of TELEPHONE  
     */
    public java.lang.String getTELEPHONE()
    {
        
        return __TELEPHONE;
    }
    
    /**
     * Set the value of TELEPHONE  
     */
    public void setTELEPHONE(java.lang.String value)
    {
        __TELEPHONE = value;
    }
    
    /**
     * get the value of PRICE_GRP  
     */
    public java.lang.String getPRICE_GRP()
    {
        
        return __PRICE_GRP;
    }
    
    /**
     * Set the value of PRICE_GRP  
     */
    public void setPRICE_GRP(java.lang.String value)
    {
        __PRICE_GRP = value;
    }
    
    /**
     * get the value of CUST_GROUP  
     */
    public java.lang.String getCUST_GROUP()
    {
        
        return __CUST_GROUP;
    }
    
    /**
     * Set the value of CUST_GROUP  
     */
    public void setCUST_GROUP(java.lang.String value)
    {
        __CUST_GROUP = value;
    }
    
    /**
     * get the value of SALES_DIST  
     */
    public java.lang.String getSALES_DIST()
    {
        
        return __SALES_DIST;
    }
    
    /**
     * Set the value of SALES_DIST  
     */
    public void setSALES_DIST(java.lang.String value)
    {
        __SALES_DIST = value;
    }
    
    /**
     * get the value of PRICE_LIST  
     */
    public java.lang.String getPRICE_LIST()
    {
        
        return __PRICE_LIST;
    }
    
    /**
     * Set the value of PRICE_LIST  
     */
    public void setPRICE_LIST(java.lang.String value)
    {
        __PRICE_LIST = value;
    }
    
    /**
     * get the value of INCOTERMS1  
     */
    public java.lang.String getINCOTERMS1()
    {
        
        return __INCOTERMS1;
    }
    
    /**
     * Set the value of INCOTERMS1  
     */
    public void setINCOTERMS1(java.lang.String value)
    {
        __INCOTERMS1 = value;
    }
    
    /**
     * get the value of INCOTERMS2  
     */
    public java.lang.String getINCOTERMS2()
    {
        
        return __INCOTERMS2;
    }
    
    /**
     * Set the value of INCOTERMS2  
     */
    public void setINCOTERMS2(java.lang.String value)
    {
        __INCOTERMS2 = value;
    }
    
    /**
     * get the value of PMNTTRMS  
     */
    public java.lang.String getPMNTTRMS()
    {
        
        return __PMNTTRMS;
    }
    
    /**
     * Set the value of PMNTTRMS  
     */
    public void setPMNTTRMS(java.lang.String value)
    {
        __PMNTTRMS = value;
    }
    
    /**
     * get the value of DLV_BLOCK  
     */
    public java.lang.String getDLV_BLOCK()
    {
        
        return __DLV_BLOCK;
    }
    
    /**
     * Set the value of DLV_BLOCK  
     */
    public void setDLV_BLOCK(java.lang.String value)
    {
        __DLV_BLOCK = value;
    }
    
    /**
     * get the value of BILL_BLOCK  
     */
    public java.lang.String getBILL_BLOCK()
    {
        
        return __BILL_BLOCK;
    }
    
    /**
     * Set the value of BILL_BLOCK  
     */
    public void setBILL_BLOCK(java.lang.String value)
    {
        __BILL_BLOCK = value;
    }
    
    /**
     * get the value of ORD_REASON  
     */
    public java.lang.String getORD_REASON()
    {
        
        return __ORD_REASON;
    }
    
    /**
     * Set the value of ORD_REASON  
     */
    public void setORD_REASON(java.lang.String value)
    {
        __ORD_REASON = value;
    }
    
    /**
     * get the value of COMPL_DLV  
     */
    public java.lang.String getCOMPL_DLV()
    {
        
        return __COMPL_DLV;
    }
    
    /**
     * Set the value of COMPL_DLV  
     */
    public void setCOMPL_DLV(java.lang.String value)
    {
        __COMPL_DLV = value;
    }
    
    /**
     * get the value of PRICE_DATE  
     */
    public java.sql.Date getPRICE_DATE()
    {
        
        return __PRICE_DATE;
    }
    
    /**
     * Set the value of PRICE_DATE  
     */
    public void setPRICE_DATE(java.sql.Date value)
    {
        __PRICE_DATE = value;
    }
    
    /**
     * get the value of QT_VALID_F  
     */
    public java.sql.Date getQT_VALID_F()
    {
        
        return __QT_VALID_F;
    }
    
    /**
     * Set the value of QT_VALID_F  
     */
    public void setQT_VALID_F(java.sql.Date value)
    {
        __QT_VALID_F = value;
    }
    
    /**
     * get the value of QT_VALID_T  
     */
    public java.sql.Date getQT_VALID_T()
    {
        
        return __QT_VALID_T;
    }
    
    /**
     * Set the value of QT_VALID_T  
     */
    public void setQT_VALID_T(java.sql.Date value)
    {
        __QT_VALID_T = value;
    }
    
    /**
     * get the value of CT_VALID_F  
     */
    public java.sql.Date getCT_VALID_F()
    {
        
        return __CT_VALID_F;
    }
    
    /**
     * Set the value of CT_VALID_F  
     */
    public void setCT_VALID_F(java.sql.Date value)
    {
        __CT_VALID_F = value;
    }
    
    /**
     * get the value of CT_VALID_T  
     */
    public java.sql.Date getCT_VALID_T()
    {
        
        return __CT_VALID_T;
    }
    
    /**
     * Set the value of CT_VALID_T  
     */
    public void setCT_VALID_T(java.sql.Date value)
    {
        __CT_VALID_T = value;
    }
    
    /**
     * get the value of CUST_GRP1  
     */
    public java.lang.String getCUST_GRP1()
    {
        
        return __CUST_GRP1;
    }
    
    /**
     * Set the value of CUST_GRP1  
     */
    public void setCUST_GRP1(java.lang.String value)
    {
        __CUST_GRP1 = value;
    }
    
    /**
     * get the value of CUST_GRP2  
     */
    public java.lang.String getCUST_GRP2()
    {
        
        return __CUST_GRP2;
    }
    
    /**
     * Set the value of CUST_GRP2  
     */
    public void setCUST_GRP2(java.lang.String value)
    {
        __CUST_GRP2 = value;
    }
    
    /**
     * get the value of CUST_GRP3  
     */
    public java.lang.String getCUST_GRP3()
    {
        
        return __CUST_GRP3;
    }
    
    /**
     * Set the value of CUST_GRP3  
     */
    public void setCUST_GRP3(java.lang.String value)
    {
        __CUST_GRP3 = value;
    }
    
    /**
     * get the value of CUST_GRP4  
     */
    public java.lang.String getCUST_GRP4()
    {
        
        return __CUST_GRP4;
    }
    
    /**
     * Set the value of CUST_GRP4  
     */
    public void setCUST_GRP4(java.lang.String value)
    {
        __CUST_GRP4 = value;
    }
    
    /**
     * get the value of CUST_GRP5  
     */
    public java.lang.String getCUST_GRP5()
    {
        
        return __CUST_GRP5;
    }
    
    /**
     * Set the value of CUST_GRP5  
     */
    public void setCUST_GRP5(java.lang.String value)
    {
        __CUST_GRP5 = value;
    }
    
    /**
     * get the value of PURCH_NO_C  
     */
    public java.lang.String getPURCH_NO_C()
    {
        
        return __PURCH_NO_C;
    }
    
    /**
     * Set the value of PURCH_NO_C  
     */
    public void setPURCH_NO_C(java.lang.String value)
    {
        __PURCH_NO_C = value;
    }
    
    /**
     * get the value of PURCH_NO_S  
     */
    public java.lang.String getPURCH_NO_S()
    {
        
        return __PURCH_NO_S;
    }
    
    /**
     * Set the value of PURCH_NO_S  
     */
    public void setPURCH_NO_S(java.lang.String value)
    {
        __PURCH_NO_S = value;
    }
    
    /**
     * get the value of PO_DAT_S  
     */
    public java.sql.Date getPO_DAT_S()
    {
        
        return __PO_DAT_S;
    }
    
    /**
     * Set the value of PO_DAT_S  
     */
    public void setPO_DAT_S(java.sql.Date value)
    {
        __PO_DAT_S = value;
    }
    
    /**
     * get the value of PO_METH_S  
     */
    public java.lang.String getPO_METH_S()
    {
        
        return __PO_METH_S;
    }
    
    /**
     * Set the value of PO_METH_S  
     */
    public void setPO_METH_S(java.lang.String value)
    {
        __PO_METH_S = value;
    }
    
    /**
     * get the value of REF_1_S  
     */
    public java.lang.String getREF_1_S()
    {
        
        return __REF_1_S;
    }
    
    /**
     * Set the value of REF_1_S  
     */
    public void setREF_1_S(java.lang.String value)
    {
        __REF_1_S = value;
    }
    
    /**
     * get the value of SD_DOC_CAT  
     */
    public java.lang.String getSD_DOC_CAT()
    {
        
        return __SD_DOC_CAT;
    }
    
    /**
     * Set the value of SD_DOC_CAT  
     */
    public void setSD_DOC_CAT(java.lang.String value)
    {
        __SD_DOC_CAT = value;
    }
    
    /**
     * get the value of DOC_DATE  
     */
    public java.sql.Date getDOC_DATE()
    {
        
        return __DOC_DATE;
    }
    
    /**
     * Set the value of DOC_DATE  
     */
    public void setDOC_DATE(java.sql.Date value)
    {
        __DOC_DATE = value;
    }
    
    /**
     * get the value of WAR_DATE  
     */
    public java.sql.Date getWAR_DATE()
    {
        
        return __WAR_DATE;
    }
    
    /**
     * Set the value of WAR_DATE  
     */
    public void setWAR_DATE(java.sql.Date value)
    {
        __WAR_DATE = value;
    }
    
    /**
     * get the value of SHIP_COND  
     */
    public java.lang.String getSHIP_COND()
    {
        
        return __SHIP_COND;
    }
    
    /**
     * Set the value of SHIP_COND  
     */
    public void setSHIP_COND(java.lang.String value)
    {
        __SHIP_COND = value;
    }
    
    /**
     * get the value of PP_SEARCH  
     */
    public java.lang.String getPP_SEARCH()
    {
        
        return __PP_SEARCH;
    }
    
    /**
     * Set the value of PP_SEARCH  
     */
    public void setPP_SEARCH(java.lang.String value)
    {
        __PP_SEARCH = value;
    }
    
    /**
     * get the value of DUN_COUNT  
     */
    public java.math.BigDecimal getDUN_COUNT()
    {
        
        return __DUN_COUNT;
    }
    
    /**
     * Set the value of DUN_COUNT  
     */
    public void setDUN_COUNT(java.math.BigDecimal value)
    {
        __DUN_COUNT = value;
    }
    
    /**
     * get the value of DUN_DATE  
     */
    public java.sql.Date getDUN_DATE()
    {
        
        return __DUN_DATE;
    }
    
    /**
     * Set the value of DUN_DATE  
     */
    public void setDUN_DATE(java.sql.Date value)
    {
        __DUN_DATE = value;
    }
    
    /**
     * get the value of DLVSCHDUSE  
     */
    public java.lang.String getDLVSCHDUSE()
    {
        
        return __DLVSCHDUSE;
    }
    
    /**
     * Set the value of DLVSCHDUSE  
     */
    public void setDLVSCHDUSE(java.lang.String value)
    {
        __DLVSCHDUSE = value;
    }
    
    /**
     * get the value of PLDLVSTYP  
     */
    public java.lang.String getPLDLVSTYP()
    {
        
        return __PLDLVSTYP;
    }
    
    /**
     * Set the value of PLDLVSTYP  
     */
    public void setPLDLVSTYP(java.lang.String value)
    {
        __PLDLVSTYP = value;
    }
    
    /**
     * get the value of REF_DOC  
     */
    public java.lang.String getREF_DOC()
    {
        
        return __REF_DOC;
    }
    
    /**
     * Set the value of REF_DOC  
     */
    public void setREF_DOC(java.lang.String value)
    {
        __REF_DOC = value;
    }
    
    /**
     * get the value of COMP_CDE_B  
     */
    public java.lang.String getCOMP_CDE_B()
    {
        
        return __COMP_CDE_B;
    }
    
    /**
     * Set the value of COMP_CDE_B  
     */
    public void setCOMP_CDE_B(java.lang.String value)
    {
        __COMP_CDE_B = value;
    }
    
    /**
     * get the value of ALTTAX_CLS  
     */
    public java.lang.String getALTTAX_CLS()
    {
        
        return __ALTTAX_CLS;
    }
    
    /**
     * Set the value of ALTTAX_CLS  
     */
    public void setALTTAX_CLS(java.lang.String value)
    {
        __ALTTAX_CLS = value;
    }
    
    /**
     * get the value of TAX_CLASS2  
     */
    public java.lang.String getTAX_CLASS2()
    {
        
        return __TAX_CLASS2;
    }
    
    /**
     * Set the value of TAX_CLASS2  
     */
    public void setTAX_CLASS2(java.lang.String value)
    {
        __TAX_CLASS2 = value;
    }
    
    /**
     * get the value of TAX_CLASS3  
     */
    public java.lang.String getTAX_CLASS3()
    {
        
        return __TAX_CLASS3;
    }
    
    /**
     * Set the value of TAX_CLASS3  
     */
    public void setTAX_CLASS3(java.lang.String value)
    {
        __TAX_CLASS3 = value;
    }
    
    /**
     * get the value of TAX_CLASS4  
     */
    public java.lang.String getTAX_CLASS4()
    {
        
        return __TAX_CLASS4;
    }
    
    /**
     * Set the value of TAX_CLASS4  
     */
    public void setTAX_CLASS4(java.lang.String value)
    {
        __TAX_CLASS4 = value;
    }
    
    /**
     * get the value of TAX_CLASS5  
     */
    public java.lang.String getTAX_CLASS5()
    {
        
        return __TAX_CLASS5;
    }
    
    /**
     * Set the value of TAX_CLASS5  
     */
    public void setTAX_CLASS5(java.lang.String value)
    {
        __TAX_CLASS5 = value;
    }
    
    /**
     * get the value of TAX_CLASS6  
     */
    public java.lang.String getTAX_CLASS6()
    {
        
        return __TAX_CLASS6;
    }
    
    /**
     * Set the value of TAX_CLASS6  
     */
    public void setTAX_CLASS6(java.lang.String value)
    {
        __TAX_CLASS6 = value;
    }
    
    /**
     * get the value of TAX_CLASS7  
     */
    public java.lang.String getTAX_CLASS7()
    {
        
        return __TAX_CLASS7;
    }
    
    /**
     * Set the value of TAX_CLASS7  
     */
    public void setTAX_CLASS7(java.lang.String value)
    {
        __TAX_CLASS7 = value;
    }
    
    /**
     * get the value of TAX_CLASS8  
     */
    public java.lang.String getTAX_CLASS8()
    {
        
        return __TAX_CLASS8;
    }
    
    /**
     * Set the value of TAX_CLASS8  
     */
    public void setTAX_CLASS8(java.lang.String value)
    {
        __TAX_CLASS8 = value;
    }
    
    /**
     * get the value of TAX_CLASS9  
     */
    public java.lang.String getTAX_CLASS9()
    {
        
        return __TAX_CLASS9;
    }
    
    /**
     * Set the value of TAX_CLASS9  
     */
    public void setTAX_CLASS9(java.lang.String value)
    {
        __TAX_CLASS9 = value;
    }
    
    /**
     * get the value of REF_DOC_L  
     */
    public java.lang.String getREF_DOC_L()
    {
        
        return __REF_DOC_L;
    }
    
    /**
     * Set the value of REF_DOC_L  
     */
    public void setREF_DOC_L(java.lang.String value)
    {
        __REF_DOC_L = value;
    }
    
    /**
     * get the value of ASS_NUMBER  
     */
    public java.lang.String getASS_NUMBER()
    {
        
        return __ASS_NUMBER;
    }
    
    /**
     * Set the value of ASS_NUMBER  
     */
    public void setASS_NUMBER(java.lang.String value)
    {
        __ASS_NUMBER = value;
    }
    
    /**
     * get the value of REFDOC_CAT  
     */
    public java.lang.String getREFDOC_CAT()
    {
        
        return __REFDOC_CAT;
    }
    
    /**
     * Set the value of REFDOC_CAT  
     */
    public void setREFDOC_CAT(java.lang.String value)
    {
        __REFDOC_CAT = value;
    }
    
    /**
     * get the value of ORDCOMB_IN  
     */
    public java.lang.String getORDCOMB_IN()
    {
        
        return __ORDCOMB_IN;
    }
    
    /**
     * Set the value of ORDCOMB_IN  
     */
    public void setORDCOMB_IN(java.lang.String value)
    {
        __ORDCOMB_IN = value;
    }
    
    /**
     * get the value of BILL_SCHED  
     */
    public java.lang.String getBILL_SCHED()
    {
        
        return __BILL_SCHED;
    }
    
    /**
     * Set the value of BILL_SCHED  
     */
    public void setBILL_SCHED(java.lang.String value)
    {
        __BILL_SCHED = value;
    }
    
    /**
     * get the value of INVO_SCHED  
     */
    public java.lang.String getINVO_SCHED()
    {
        
        return __INVO_SCHED;
    }
    
    /**
     * Set the value of INVO_SCHED  
     */
    public void setINVO_SCHED(java.lang.String value)
    {
        __INVO_SCHED = value;
    }
    
    /**
     * get the value of MN_INVOICE  
     */
    public java.lang.String getMN_INVOICE()
    {
        
        return __MN_INVOICE;
    }
    
    /**
     * Set the value of MN_INVOICE  
     */
    public void setMN_INVOICE(java.lang.String value)
    {
        __MN_INVOICE = value;
    }
    
    /**
     * get the value of EXRATE_FI  
     */
    public java.math.BigDecimal getEXRATE_FI()
    {
        
        return __EXRATE_FI;
    }
    
    /**
     * Set the value of EXRATE_FI  
     */
    public void setEXRATE_FI(java.math.BigDecimal value)
    {
        __EXRATE_FI = value;
    }
    
    /**
     * get the value of ADD_VAL_DY  
     */
    public java.lang.String getADD_VAL_DY()
    {
        
        return __ADD_VAL_DY;
    }
    
    /**
     * Set the value of ADD_VAL_DY  
     */
    public void setADD_VAL_DY(java.lang.String value)
    {
        __ADD_VAL_DY = value;
    }
    
    /**
     * get the value of FIX_VAL_DY  
     */
    public java.sql.Date getFIX_VAL_DY()
    {
        
        return __FIX_VAL_DY;
    }
    
    /**
     * Set the value of FIX_VAL_DY  
     */
    public void setFIX_VAL_DY(java.sql.Date value)
    {
        __FIX_VAL_DY = value;
    }
    
    /**
     * get the value of PYMT_METH  
     */
    public java.lang.String getPYMT_METH()
    {
        
        return __PYMT_METH;
    }
    
    /**
     * Set the value of PYMT_METH  
     */
    public void setPYMT_METH(java.lang.String value)
    {
        __PYMT_METH = value;
    }
    
    /**
     * get the value of ACCNT_ASGN  
     */
    public java.lang.String getACCNT_ASGN()
    {
        
        return __ACCNT_ASGN;
    }
    
    /**
     * Set the value of ACCNT_ASGN  
     */
    public void setACCNT_ASGN(java.lang.String value)
    {
        __ACCNT_ASGN = value;
    }
    
    /**
     * get the value of EXCHG_RATE  
     */
    public java.math.BigDecimal getEXCHG_RATE()
    {
        
        return __EXCHG_RATE;
    }
    
    /**
     * Set the value of EXCHG_RATE  
     */
    public void setEXCHG_RATE(java.math.BigDecimal value)
    {
        __EXCHG_RATE = value;
    }
    
    /**
     * get the value of BILL_DATE  
     */
    public java.sql.Date getBILL_DATE()
    {
        
        return __BILL_DATE;
    }
    
    /**
     * Set the value of BILL_DATE  
     */
    public void setBILL_DATE(java.sql.Date value)
    {
        __BILL_DATE = value;
    }
    
    /**
     * get the value of SERV_DATE  
     */
    public java.sql.Date getSERV_DATE()
    {
        
        return __SERV_DATE;
    }
    
    /**
     * Set the value of SERV_DATE  
     */
    public void setSERV_DATE(java.sql.Date value)
    {
        __SERV_DATE = value;
    }
    
    /**
     * get the value of DUNN_KEY  
     */
    public java.lang.String getDUNN_KEY()
    {
        
        return __DUNN_KEY;
    }
    
    /**
     * Set the value of DUNN_KEY  
     */
    public void setDUNN_KEY(java.lang.String value)
    {
        __DUNN_KEY = value;
    }
    
    /**
     * get the value of DUNN_BLOCK  
     */
    public java.lang.String getDUNN_BLOCK()
    {
        
        return __DUNN_BLOCK;
    }
    
    /**
     * Set the value of DUNN_BLOCK  
     */
    public void setDUNN_BLOCK(java.lang.String value)
    {
        __DUNN_BLOCK = value;
    }
    
    /**
     * get the value of PMTGAR_PRO  
     */
    public java.lang.String getPMTGAR_PRO()
    {
        
        return __PMTGAR_PRO;
    }
    
    /**
     * Set the value of PMTGAR_PRO  
     */
    public void setPMTGAR_PRO(java.lang.String value)
    {
        __PMTGAR_PRO = value;
    }
    
    /**
     * get the value of DEPARTM_NO  
     */
    public java.lang.String getDEPARTM_NO()
    {
        
        return __DEPARTM_NO;
    }
    
    /**
     * Set the value of DEPARTM_NO  
     */
    public void setDEPARTM_NO(java.lang.String value)
    {
        __DEPARTM_NO = value;
    }
    
    /**
     * get the value of REC_POINT  
     */
    public java.lang.String getREC_POINT()
    {
        
        return __REC_POINT;
    }
    
    /**
     * Set the value of REC_POINT  
     */
    public void setREC_POINT(java.lang.String value)
    {
        __REC_POINT = value;
    }
    
    /**
     * get the value of DOC_NUM_FI  
     */
    public java.lang.String getDOC_NUM_FI()
    {
        
        return __DOC_NUM_FI;
    }
    
    /**
     * Set the value of DOC_NUM_FI  
     */
    public void setDOC_NUM_FI(java.lang.String value)
    {
        __DOC_NUM_FI = value;
    }
    
    /**
     * get the value of CSTCNDGRP1  
     */
    public java.lang.String getCSTCNDGRP1()
    {
        
        return __CSTCNDGRP1;
    }
    
    /**
     * Set the value of CSTCNDGRP1  
     */
    public void setCSTCNDGRP1(java.lang.String value)
    {
        __CSTCNDGRP1 = value;
    }
    
    /**
     * get the value of CSTCNDGRP2  
     */
    public java.lang.String getCSTCNDGRP2()
    {
        
        return __CSTCNDGRP2;
    }
    
    /**
     * Set the value of CSTCNDGRP2  
     */
    public void setCSTCNDGRP2(java.lang.String value)
    {
        __CSTCNDGRP2 = value;
    }
    
    /**
     * get the value of CSTCNDGRP3  
     */
    public java.lang.String getCSTCNDGRP3()
    {
        
        return __CSTCNDGRP3;
    }
    
    /**
     * Set the value of CSTCNDGRP3  
     */
    public void setCSTCNDGRP3(java.lang.String value)
    {
        __CSTCNDGRP3 = value;
    }
    
    /**
     * get the value of CSTCNDGRP4  
     */
    public java.lang.String getCSTCNDGRP4()
    {
        
        return __CSTCNDGRP4;
    }
    
    /**
     * Set the value of CSTCNDGRP4  
     */
    public void setCSTCNDGRP4(java.lang.String value)
    {
        __CSTCNDGRP4 = value;
    }
    
    /**
     * get the value of CSTCNDGRP5  
     */
    public java.lang.String getCSTCNDGRP5()
    {
        
        return __CSTCNDGRP5;
    }
    
    /**
     * Set the value of CSTCNDGRP5  
     */
    public void setCSTCNDGRP5(java.lang.String value)
    {
        __CSTCNDGRP5 = value;
    }
    
    /**
     * get the value of DLV_TIME  
     */
    public java.lang.String getDLV_TIME()
    {
        
        return __DLV_TIME;
    }
    
    /**
     * Set the value of DLV_TIME  
     */
    public void setDLV_TIME(java.lang.String value)
    {
        __DLV_TIME = value;
    }
    
    /**
     * get the value of CURRENCY  
     */
    public java.lang.String getCURRENCY()
    {
        
        return __CURRENCY;
    }
    
    /**
     * Set the value of CURRENCY  
     */
    public void setCURRENCY(java.lang.String value)
    {
        __CURRENCY = value;
    }
    
    /**
     * get the value of CURR_ISO  
     */
    public java.lang.String getCURR_ISO()
    {
        
        return __CURR_ISO;
    }
    
    /**
     * Set the value of CURR_ISO  
     */
    public void setCURR_ISO(java.lang.String value)
    {
        __CURR_ISO = value;
    }
    
    /**
     * get the value of CREATED_BY  
     */
    public java.lang.String getCREATED_BY()
    {
        
        return __CREATED_BY;
    }
    
    /**
     * Set the value of CREATED_BY  
     */
    public void setCREATED_BY(java.lang.String value)
    {
        __CREATED_BY = value;
    }
    
    /**
     * get the value of TAXDEP_CTY  
     */
    public java.lang.String getTAXDEP_CTY()
    {
        
        return __TAXDEP_CTY;
    }
    
    /**
     * Set the value of TAXDEP_CTY  
     */
    public void setTAXDEP_CTY(java.lang.String value)
    {
        __TAXDEP_CTY = value;
    }
    
    /**
     * get the value of TAXDST_CTY  
     */
    public java.lang.String getTAXDST_CTY()
    {
        
        return __TAXDST_CTY;
    }
    
    /**
     * Set the value of TAXDST_CTY  
     */
    public void setTAXDST_CTY(java.lang.String value)
    {
        __TAXDST_CTY = value;
    }
    
    /**
     * get the value of EUTRI_DEAL  
     */
    public java.lang.String getEUTRI_DEAL()
    {
        
        return __EUTRI_DEAL;
    }
    
    /**
     * Set the value of EUTRI_DEAL  
     */
    public void setEUTRI_DEAL(java.lang.String value)
    {
        __EUTRI_DEAL = value;
    }
    
    /**
     * get the value of MAST_CONTR  
     */
    public java.lang.String getMAST_CONTR()
    {
        
        return __MAST_CONTR;
    }
    
    /**
     * Set the value of MAST_CONTR  
     */
    public void setMAST_CONTR(java.lang.String value)
    {
        __MAST_CONTR = value;
    }
    
    /**
     * get the value of REF_PROC  
     */
    public java.lang.String getREF_PROC()
    {
        
        return __REF_PROC;
    }
    
    /**
     * Set the value of REF_PROC  
     */
    public void setREF_PROC(java.lang.String value)
    {
        __REF_PROC = value;
    }
    
    /**
     * get the value of CHKPRTAUTH  
     */
    public java.lang.String getCHKPRTAUTH()
    {
        
        return __CHKPRTAUTH;
    }
    
    /**
     * Set the value of CHKPRTAUTH  
     */
    public void setCHKPRTAUTH(java.lang.String value)
    {
        __CHKPRTAUTH = value;
    }
    
    /**
     * get the value of CMLQTY_DAT  
     */
    public java.sql.Date getCMLQTY_DAT()
    {
        
        return __CMLQTY_DAT;
    }
    
    /**
     * Set the value of CMLQTY_DAT  
     */
    public void setCMLQTY_DAT(java.sql.Date value)
    {
        __CMLQTY_DAT = value;
    }
    
    /**
     * get the value of VERSION  
     */
    public java.lang.String getVERSION()
    {
        
        return __VERSION;
    }
    
    /**
     * Set the value of VERSION  
     */
    public void setVERSION(java.lang.String value)
    {
        __VERSION = value;
    }
    
    /**
     * get the value of NOTIF_NO  
     */
    public java.lang.String getNOTIF_NO()
    {
        
        return __NOTIF_NO;
    }
    
    /**
     * Set the value of NOTIF_NO  
     */
    public void setNOTIF_NO(java.lang.String value)
    {
        __NOTIF_NO = value;
    }
    
    /**
     * get the value of WBS_ELEM  
     */
    public java.lang.String getWBS_ELEM()
    {
        
        return __WBS_ELEM;
    }
    
    /**
     * Set the value of WBS_ELEM  
     */
    public void setWBS_ELEM(java.lang.String value)
    {
        __WBS_ELEM = value;
    }
    
    /**
     * get the value of EXCH_RATE_FI_V  
     */
    public java.math.BigDecimal getEXCH_RATE_FI_V()
    {
        
        return __EXCH_RATE_FI_V;
    }
    
    /**
     * Set the value of EXCH_RATE_FI_V  
     */
    public void setEXCH_RATE_FI_V(java.math.BigDecimal value)
    {
        __EXCH_RATE_FI_V = value;
    }
    
    /**
     * get the value of EXCHG_RATE_V  
     */
    public java.math.BigDecimal getEXCHG_RATE_V()
    {
        
        return __EXCHG_RATE_V;
    }
    
    /**
     * Set the value of EXCHG_RATE_V  
     */
    public void setEXCHG_RATE_V(java.math.BigDecimal value)
    {
        __EXCHG_RATE_V = value;
    }
    
    /**
     * get the value of FKK_CONACCT  
     */
    public java.lang.String getFKK_CONACCT()
    {
        
        return __FKK_CONACCT;
    }
    
    /**
     * Set the value of FKK_CONACCT  
     */
    public void setFKK_CONACCT(java.lang.String value)
    {
        __FKK_CONACCT = value;
    }
    
    /**
     * get the value of CAMPAIGN  
     */
    public byte[] getCAMPAIGN()
    {
        
        return __CAMPAIGN;
    }
    
    /**
     * Set the value of CAMPAIGN  
     */
    public void setCAMPAIGN(byte[] value)
    {
        __CAMPAIGN = value;
    }
    
    /**
     * get the value of DOC_CLASS  
     */
    public java.lang.String getDOC_CLASS()
    {
        
        return __DOC_CLASS;
    }
    
    /**
     * Set the value of DOC_CLASS  
     */
    public void setDOC_CLASS(java.lang.String value)
    {
        __DOC_CLASS = value;
    }
    
    /**
     * get the value of H_CURR  
     */
    public java.lang.String getH_CURR()
    {
        
        return __H_CURR;
    }
    
    /**
     * Set the value of H_CURR  
     */
    public void setH_CURR(java.lang.String value)
    {
        __H_CURR = value;
    }
    
    /**
     * get the value of H_CURR_ISO  
     */
    public java.lang.String getH_CURR_ISO()
    {
        
        return __H_CURR_ISO;
    }
    
    /**
     * Set the value of H_CURR_ISO  
     */
    public void setH_CURR_ISO(java.lang.String value)
    {
        __H_CURR_ISO = value;
    }
    
    /**
     * get the value of SHIP_TYPE  
     */
    public java.lang.String getSHIP_TYPE()
    {
        
        return __SHIP_TYPE;
    }
    
    /**
     * Set the value of SHIP_TYPE  
     */
    public void setSHIP_TYPE(java.lang.String value)
    {
        __SHIP_TYPE = value;
    }
    
    /**
     * get the value of S_PROC_IND  
     */
    public java.lang.String getS_PROC_IND()
    {
        
        return __S_PROC_IND;
    }
    
    /**
     * Set the value of S_PROC_IND  
     */
    public void setS_PROC_IND(java.lang.String value)
    {
        __S_PROC_IND = value;
    }
    
    /**
     * get the value of REF_DOC_L_LONG  
     */
    public java.lang.String getREF_DOC_L_LONG()
    {
        
        return __REF_DOC_L_LONG;
    }
    
    /**
     * Set the value of REF_DOC_L_LONG  
     */
    public void setREF_DOC_L_LONG(java.lang.String value)
    {
        __REF_DOC_L_LONG = value;
    }
    
    /**
     * get the value of LINE_TIME  
     */
    public java.sql.Time getLINE_TIME()
    {
        
        return __LINE_TIME;
    }
    
    /**
     * Set the value of LINE_TIME  
     */
    public void setLINE_TIME(java.sql.Time value)
    {
        __LINE_TIME = value;
    }
    
    /**
     * get the value of CALC_MOTIVE  
     */
    public java.lang.String getCALC_MOTIVE()
    {
        
        return __CALC_MOTIVE;
    }
    
    /**
     * Set the value of CALC_MOTIVE  
     */
    public void setCALC_MOTIVE(java.lang.String value)
    {
        __CALC_MOTIVE = value;
    }
}