package GBI_SalesApp;

/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
public abstract class EntityType
{
    public static int CustomerGetDetails = 1;
    public static int SalesOrderCreate = 7;
    public static int SalesOrderGetList = 8;
    public static int SalesOrderGetStatus = 9;
}