/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class KeyGenerator extends com.sybase.sup.client.persistence.RbsKeyGenerator implements com.sybase.reflection.ClassWithMetaData
{
    static
    {
        kgMap.put("gbi_salesapp:1.0", new GBI_SalesApp.KeyGenerator());
    }
    
    public KeyGenerator()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getDelegate(), "gbi_salesapp_1_0_keygenerator", 100000);
    }
    
    /** Begin code region: MetaData **/
    private static GBI_SalesApp.intrnl.KeyGeneratorMetaData META_DATA = new GBI_SalesApp.intrnl.KeyGeneratorMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("KeyGenerator", GBI_SalesApp.KeyGenerator.class, "GBI_SalesApp.KeyGenerator", META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
        
    /**
     * Generate surrogate key.  
     */
    public static long generateId()
    {
        return GBI_SalesApp.GBI_SalesAppDB.getDelegate().generateId();
    }
}