/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.1.3.358
 * mbs - false 
 */
package GBI_SalesApp;

public  class LocalKeyGenerator extends com.sybase.sup.client.persistence.LocalKeyGenerator implements com.sybase.reflection.ClassWithMetaData
{
    static
    {
        kgMap.put("gbi_salesapp:1.0", new GBI_SalesApp.LocalKeyGenerator());
    }
    
    public LocalKeyGenerator()
    {
        super(GBI_SalesApp.GBI_SalesAppDB.getDelegate(), "co_gbi_salesapp_1_0_localkeygenerator", 100000);
    }
    
    /** Begin code region: MetaData **/
    private static GBI_SalesApp.intrnl.LocalKeyGeneratorMetaData META_DATA = new GBI_SalesApp.intrnl.LocalKeyGeneratorMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("LocalKeyGenerator", GBI_SalesApp.LocalKeyGenerator.class, "GBI_SalesApp.LocalKeyGenerator", META_DATA, GBI_SalesApp.GBI_SalesAppDB.getDelegate());
        
    /**
     * Generate surrogate key.  
     */
    public static long generateId()
    {
        return GBI_SalesApp.GBI_SalesAppDB.getDelegate().generateLocalId();
    }
    
    public static String generateGuid()
    {
    	return com.sybase.afx.util.StringUtil.guid32();
    }
}